(define (problem num-gripper-x-12)
   (:domain multi-gripper-num)
   (:objects rooma roomb roomc roomd roome - room 
             ball26 ball25 ball24 ball23 ball22 ball21 ball20 ball19
             ball18 ball17 ball16 ball15 ball14 ball13 ball12 ball11 ball10
             ball9 ball8 ball7 ball6 ball5 ball4 ball3 ball2 ball1 - ball 
             r1 r2 r3 - robby
             left1 right1 left2 right2 left3 right3 - gripper)
             
   (:init (= (weight ball26) 3)
          (= (weight ball25) 3)
          (= (weight ball24) 2)
          (= (weight ball23) 2)
          (= (weight ball22) 2)
          (= (weight ball21) 2)
          (= (weight ball20) 2)
          (= (weight ball19) 2)
          (= (weight ball18) 1)
          (= (weight ball17) 1)
          (= (weight ball16) 1)
          (= (weight ball15) 1)
          (= (weight ball14) 1)
          (= (weight ball13) 1)
          (= (weight ball12) 1)
          (= (weight ball11) 1)
          (= (weight ball10) 1)
          (= (weight ball9) 1)
          (= (weight ball8) 1)
          (= (weight ball7) 1)
          (= (weight ball6) 1)
          (= (weight ball5) 1)
          (= (weight ball4) 1)
          (= (weight ball3) 1)
          (= (weight ball2) 1)
          (= (weight ball1) 1)

          (at ball26 rooma)
          (at ball25 rooma)
          (at ball24 rooma)
          (at ball23 rooma)
          (at ball22 rooma)
          (at ball21 rooma)
          (at ball20 rooma)
          (at ball19 rooma)
          (at ball18 rooma)
          (at ball17 rooma)
          (at ball16 rooma)
          (at ball15 rooma)
          (at ball14 rooma)
          (at ball13 rooma)
          (at ball12 rooma)
          (at ball11 rooma)
          (at ball10 rooma)
          (at ball9 rooma)
          (at ball8 rooma)
          (at ball7 rooma)
          (at ball6 rooma)
          (at ball5 rooma)
          (at ball4 rooma)
          (at ball3 rooma)
          (at ball2 rooma)
          (at ball1 rooma)
          
          (at-robby r1 rooma)
          (at-robby r2 rooma)
          (at-robby r3 rooma)
          (free left1)
          (free right1)
          (free left2)
          (free right2)
          (free left3)
          (free right3)
          (mount left1 r1)
          (mount right1 r1)
          (mount left2 r2)
          (mount right2 r2)
          (mount left3 r3)
          (mount right3 r3)
          
          (door rooma roomb)
          (door roomb roomc)
          (door roomc roomd)
          (door roomd roome)
          (door roome rooma)
          
          (= (current_load r1) 0)
          (= (load_limit r1) 6)
          (= (current_load r2) 0)
          (= (load_limit r2) 6)
          (= (current_load r3) 0)
          (= (load_limit r3) 6)
          (= (cost) 0)
          )
   (:goal (and (at ball26 roomb)
               (at ball25 roomb)
               (at ball24 roomb)
               (at ball23 roomb)
               (at ball22 roomc)
               (at ball21 roomc)
               (at ball20 roomc)
               (at ball19 roomc)
               (at ball18 roomd)
               (at ball17 roomd)
               (at ball16 roomd)
               (at ball15 roomd)
               (at ball14 roome)
               (at ball13 roome)
               (at ball12 roome)
               (at ball11 roome)
               (at ball10 roome)
               (at ball9 roome)
               (at ball8 roome)
               (at ball7 roome)
               (at ball6 roome)
               (at ball5 roome)
               (at ball4 roome)
               (at ball3 roome)
               (at ball2 roome)
               (at ball1 roome)))
               
               (:metric minimize (cost))
               
)
