(define (problem num-gripper-x-15)
   (:domain multi-gripper-num)
   (:objects rooma roomb roomc roomd roome roomf - room 
             ball32 ball31 ball30 ball29 ball28
             ball27 ball26 ball25 ball24 ball23 ball22 ball21 ball20 ball19
             ball18 ball17 ball16 ball15 ball14 ball13 ball12 ball11 ball10
             ball9 ball8 ball7 ball6 ball5 ball4 ball3 ball2 ball1 - ball 
             r1 r2 r3 - robby
             left1 right1 left2 right2 left3 right3 - gripper)
             
   (:init (= (weight ball32) 4)
          (= (weight ball31) 4)
          (= (weight ball30) 4)
          (= (weight ball29) 4)
          (= (weight ball28) 4)
          (= (weight ball27) 4)
          (= (weight ball26) 4)
          (= (weight ball25) 4)
          (= (weight ball24) 3)
          (= (weight ball23) 3)
          (= (weight ball22) 3)
          (= (weight ball21) 3)
          (= (weight ball20) 3)
          (= (weight ball19) 3)
          (= (weight ball18) 3)
          (= (weight ball17) 3)
          (= (weight ball16) 2)
          (= (weight ball15) 2)
          (= (weight ball14) 2)
          (= (weight ball13) 2)
          (= (weight ball12) 2)
          (= (weight ball11) 2)
          (= (weight ball10) 2)
          (= (weight ball9) 2)
          (= (weight ball8) 1)
          (= (weight ball7) 1)
          (= (weight ball6) 1)
          (= (weight ball5) 1)
          (= (weight ball4) 1)
          (= (weight ball3) 1)
          (= (weight ball2) 1)
          (= (weight ball1) 1)

          (at ball32 rooma)
          (at ball31 rooma)
          (at ball30 rooma)
          (at ball29 rooma)
          (at ball28 rooma)
          (at ball27 rooma)
          (at ball26 rooma)
          (at ball25 rooma)
          (at ball24 rooma)
          (at ball23 rooma)
          (at ball22 rooma)
          (at ball21 rooma)
          (at ball20 rooma)
          (at ball19 rooma)
          (at ball18 rooma)
          (at ball17 rooma)
          (at ball16 rooma)
          (at ball15 rooma)
          (at ball14 rooma)
          (at ball13 rooma)
          (at ball12 rooma)
          (at ball11 rooma)
          (at ball10 rooma)
          (at ball9 rooma)
          (at ball8 rooma)
          (at ball7 rooma)
          (at ball6 rooma)
          (at ball5 rooma)
          (at ball4 rooma)
          (at ball3 rooma)
          (at ball2 rooma)
          (at ball1 rooma)
          
          (at-robby r1 rooma)
          (at-robby r2 rooma)
          (at-robby r3 rooma)
          (free left1)
          (free right1)
          (free left2)
          (free right2)
          (free left3)
          (free right3)
          (mount left1 r1)
          (mount right1 r1)
          (mount left2 r2)
          (mount right2 r2)
          (mount left3 r3)
          (mount right3 r3)
          
          (door rooma roomb)
          (door roomb roomc)
          (door roomc roomd)
          (door roomd roome)
          (door roome rooma)
          (door rooma roomf)
          (door roomf roomd)
          
          (= (current_load r1) 0)
          (= (load_limit r1) 20)
          (= (current_load r2) 0)
          (= (load_limit r2) 20)
          (= (current_load r3) 0)
          (= (load_limit r3) 20)
          (= (cost) 0)
          )
   (:goal (and (at ball32 roome)
               (at ball31 roome)
               (at ball30 roome)
               (at ball29 roome)
               (at ball28 roome)
               (at ball27 roome)
               (at ball26 roome)
               (at ball25 roome)
               (at ball24 roome)
               (at ball23 roome)
               (at ball22 roome)
               (at ball21 roome)
               (at ball20 roome)
               (at ball19 roome)
               (at ball18 roome)
               (at ball17 roome)
               (at ball16 roome)
               (at ball15 roome)
               (at ball14 roome)
               (at ball13 roome)
               (at ball12 roome)
               (at ball11 roome)
               (at ball10 roome)
               (at ball9 roome)
               (at ball8 roome)
               (at ball7 roome)
               (at ball6 roome)
               (at ball5 roome)
               (at ball4 roome)
               (at ball3 roome)
               (at ball2 roome)
               (at ball1 roome)))
               
               (:metric minimize (cost))
               
)
