(define (problem depotprob4321) (:domain depot)
(:objects
	a1 a2 - agent
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 - crate
	hoist0 hoist1 hoist2 - hoist)
(:init
	(located pallet0 depot0)
	(clear crate2)
	(located pallet1 distributor0)
	(clear crate6)
	(located pallet2 distributor1)
	(clear crate9)
	(located pallet3 distributor1)
	(clear crate7)
	(located pallet4 distributor0)
	(clear crate0)
	(located pallet5 distributor0)
	(clear crate8)
	(located truck0 distributor0)
	(= (current_load truck0) 0)
	(= (load_limit truck0) 20)
	(located truck1 distributor0)
	(= (current_load truck1) 0)
	(= (load_limit truck1) 20)
	(located hoist0 depot0)
	(available hoist0)
	(located hoist1 distributor0)
	(available hoist1)
	(located hoist2 distributor1)
	(available hoist2)
	(located crate0 distributor0)
	(on crate0 pallet4)
	(= (weight crate0) 8)
	(located crate1 distributor0)
	(on crate1 pallet1)
	(= (weight crate1) 8)
	(located crate2 depot0)
	(on crate2 pallet0)
	(= (weight crate2) 8)
	(located crate3 distributor0)
	(on crate3 pallet5)
	(= (weight crate3) 8)
	(located crate4 distributor1)
	(on crate4 pallet3)
	(= (weight crate4) 8)
	(located crate5 distributor0)
	(on crate5 crate1)
	(= (weight crate5) 4)
	(located crate6 distributor0)
	(on crate6 crate5)
	(= (weight crate6) 4)
	(located crate7 distributor1)
	(on crate7 crate4)
	(= (weight crate7) 4)
	(located crate8 distributor0)
	(on crate8 crate3)
	(= (weight crate8) 4)
	(located crate9 distributor1)
	(on crate9 pallet2)
	(= (weight crate9) 4)
	(= (fuel-cost) 0)
)

(:goal (and
		(on crate0 pallet3)
		(on crate1 crate0)
		(on crate3 crate2)
		(on crate6 pallet2)
		(on crate7 pallet1)
		(on crate2 pallet4)
		(on crate9 pallet0)
	)
)

; (:metric minimize (fuel-cost))
)
