(define (problem roverprob4621) (:domain rover)
(:objects
	general - lander
	colour high-res low-res - mode
	rover0 rover1 rover2 rover3 rover4 rover5 - agent
	rover0store rover1store rover2store rover3store rover4store rover5store - store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 - waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 - camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 - objective
	)
(:init
	(visible waypoint0 waypoint1)
	(visible waypoint1 waypoint0)
	(visible waypoint0 waypoint2)
	(visible waypoint2 waypoint0)
	(visible waypoint0 waypoint12)
	(visible waypoint12 waypoint0)
	(visible waypoint0 waypoint13)
	(visible waypoint13 waypoint0)
	(visible waypoint1 waypoint2)
	(visible waypoint2 waypoint1)
	(visible waypoint1 waypoint6)
	(visible waypoint6 waypoint1)
	(visible waypoint1 waypoint11)
	(visible waypoint11 waypoint1)
	(visible waypoint1 waypoint15)
	(visible waypoint15 waypoint1)
	(visible waypoint2 waypoint6)
	(visible waypoint6 waypoint2)
	(visible waypoint2 waypoint9)
	(visible waypoint9 waypoint2)
	(visible waypoint2 waypoint14)
	(visible waypoint14 waypoint2)
	(visible waypoint2 waypoint16)
	(visible waypoint16 waypoint2)
	(visible waypoint2 waypoint18)
	(visible waypoint18 waypoint2)
	(visible waypoint3 waypoint7)
	(visible waypoint7 waypoint3)
	(visible waypoint3 waypoint11)
	(visible waypoint11 waypoint3)
	(visible waypoint3 waypoint13)
	(visible waypoint13 waypoint3)
	(visible waypoint3 waypoint15)
	(visible waypoint15 waypoint3)
	(visible waypoint4 waypoint5)
	(visible waypoint5 waypoint4)
	(visible waypoint4 waypoint9)
	(visible waypoint9 waypoint4)
	(visible waypoint4 waypoint12)
	(visible waypoint12 waypoint4)
	(visible waypoint4 waypoint18)
	(visible waypoint18 waypoint4)
	(visible waypoint5 waypoint6)
	(visible waypoint6 waypoint5)
	(visible waypoint5 waypoint10)
	(visible waypoint10 waypoint5)
	(visible waypoint5 waypoint12)
	(visible waypoint12 waypoint5)
	(visible waypoint5 waypoint14)
	(visible waypoint14 waypoint5)
	(visible waypoint6 waypoint3)
	(visible waypoint3 waypoint6)
	(visible waypoint6 waypoint12)
	(visible waypoint12 waypoint6)
	(visible waypoint6 waypoint13)
	(visible waypoint13 waypoint6)
	(visible waypoint6 waypoint14)
	(visible waypoint14 waypoint6)
	(visible waypoint6 waypoint19)
	(visible waypoint19 waypoint6)
	(visible waypoint7 waypoint1)
	(visible waypoint1 waypoint7)
	(visible waypoint7 waypoint2)
	(visible waypoint2 waypoint7)
	(visible waypoint7 waypoint5)
	(visible waypoint5 waypoint7)
	(visible waypoint7 waypoint9)
	(visible waypoint9 waypoint7)
	(visible waypoint8 waypoint14)
	(visible waypoint14 waypoint8)
	(visible waypoint9 waypoint0)
	(visible waypoint0 waypoint9)
	(visible waypoint9 waypoint3)
	(visible waypoint3 waypoint9)
	(visible waypoint9 waypoint5)
	(visible waypoint5 waypoint9)
	(visible waypoint9 waypoint6)
	(visible waypoint6 waypoint9)
	(visible waypoint9 waypoint8)
	(visible waypoint8 waypoint9)
	(visible waypoint9 waypoint12)
	(visible waypoint12 waypoint9)
	(visible waypoint10 waypoint3)
	(visible waypoint3 waypoint10)
	(visible waypoint10 waypoint7)
	(visible waypoint7 waypoint10)
	(visible waypoint10 waypoint8)
	(visible waypoint8 waypoint10)
	(visible waypoint10 waypoint9)
	(visible waypoint9 waypoint10)
	(visible waypoint10 waypoint16)
	(visible waypoint16 waypoint10)
	(visible waypoint11 waypoint4)
	(visible waypoint4 waypoint11)
	(visible waypoint11 waypoint5)
	(visible waypoint5 waypoint11)
	(visible waypoint11 waypoint7)
	(visible waypoint7 waypoint11)
	(visible waypoint11 waypoint12)
	(visible waypoint12 waypoint11)
	(visible waypoint11 waypoint16)
	(visible waypoint16 waypoint11)
	(visible waypoint12 waypoint1)
	(visible waypoint1 waypoint12)
	(visible waypoint12 waypoint8)
	(visible waypoint8 waypoint12)
	(visible waypoint12 waypoint14)
	(visible waypoint14 waypoint12)
	(visible waypoint12 waypoint19)
	(visible waypoint19 waypoint12)
	(visible waypoint13 waypoint4)
	(visible waypoint4 waypoint13)
	(visible waypoint13 waypoint19)
	(visible waypoint19 waypoint13)
	(visible waypoint14 waypoint9)
	(visible waypoint9 waypoint14)
	(visible waypoint14 waypoint15)
	(visible waypoint15 waypoint14)
	(visible waypoint15 waypoint6)
	(visible waypoint6 waypoint15)
	(visible waypoint16 waypoint0)
	(visible waypoint0 waypoint16)
	(visible waypoint16 waypoint12)
	(visible waypoint12 waypoint16)
	(visible waypoint16 waypoint13)
	(visible waypoint13 waypoint16)
	(visible waypoint17 waypoint0)
	(visible waypoint0 waypoint17)
	(visible waypoint17 waypoint11)
	(visible waypoint11 waypoint17)
	(visible waypoint18 waypoint0)
	(visible waypoint0 waypoint18)
	(visible waypoint18 waypoint9)
	(visible waypoint9 waypoint18)
	(visible waypoint18 waypoint11)
	(visible waypoint11 waypoint18)
	(visible waypoint19 waypoint9)
	(visible waypoint9 waypoint19)
	(visible waypoint19 waypoint14)
	(visible waypoint14 waypoint19)
	(visible waypoint19 waypoint15)
	(visible waypoint15 waypoint19)
	(visible waypoint19 waypoint16)
	(visible waypoint16 waypoint19)
	(visible waypoint19 waypoint17)
	(visible waypoint17 waypoint19)
	(= (recharges) 0)
	(at-soil-sample waypoint0)
	(at-rock-sample waypoint1)
	(at-rock-sample waypoint2)
	(at-soil-sample waypoint3)
	(in-sun waypoint3)
	(at-rock-sample waypoint4)
	(in-sun waypoint4)
	(at-rock-sample waypoint5)
	(at-rock-sample waypoint6)
	(at-rock-sample waypoint7)
	(at-soil-sample waypoint8)
	(at-soil-sample waypoint9)
	(at-rock-sample waypoint9)
	(in-sun waypoint9)
	(at-soil-sample waypoint10)
	(in-sun waypoint10)
	(at-soil-sample waypoint11)
	(at-soil-sample waypoint12)
	(at-rock-sample waypoint12)
	(at-soil-sample waypoint13)
	(at-rock-sample waypoint13)
	(at-soil-sample waypoint14)
	(at-soil-sample waypoint15)
	(in-sun waypoint16)
	(at-soil-sample waypoint17)
	(at-rock-sample waypoint17)
	(at-soil-sample waypoint18)
	(at-rock-sample waypoint18)
	(in-sun waypoint18)
	(at-soil-sample waypoint19)
	(at-lander general waypoint17)
	(channel-free general)
	(= (energy rover0) 50)
	(in rover0 waypoint2)
	(available rover0)
	(store-of rover0store rover0)
	(empty rover0store)
	(equipped-for-soil-analysis rover0)
	(equipped-for-rock-analysis rover0)
	(equipped-for-imaging rover0)
	(can-traverse rover0 waypoint2 waypoint0)
	(can-traverse rover0 waypoint0 waypoint2)
	(can-traverse rover0 waypoint2 waypoint6)
	(can-traverse rover0 waypoint6 waypoint2)
	(can-traverse rover0 waypoint2 waypoint7)
	(can-traverse rover0 waypoint7 waypoint2)
	(can-traverse rover0 waypoint2 waypoint9)
	(can-traverse rover0 waypoint9 waypoint2)
	(can-traverse rover0 waypoint2 waypoint14)
	(can-traverse rover0 waypoint14 waypoint2)
	(can-traverse rover0 waypoint2 waypoint18)
	(can-traverse rover0 waypoint18 waypoint2)
	(can-traverse rover0 waypoint0 waypoint12)
	(can-traverse rover0 waypoint12 waypoint0)
	(can-traverse rover0 waypoint0 waypoint13)
	(can-traverse rover0 waypoint13 waypoint0)
	(can-traverse rover0 waypoint6 waypoint1)
	(can-traverse rover0 waypoint1 waypoint6)
	(can-traverse rover0 waypoint6 waypoint15)
	(can-traverse rover0 waypoint15 waypoint6)
	(can-traverse rover0 waypoint6 waypoint19)
	(can-traverse rover0 waypoint19 waypoint6)
	(can-traverse rover0 waypoint7 waypoint3)
	(can-traverse rover0 waypoint3 waypoint7)
	(can-traverse rover0 waypoint7 waypoint11)
	(can-traverse rover0 waypoint11 waypoint7)
	(can-traverse rover0 waypoint9 waypoint4)
	(can-traverse rover0 waypoint4 waypoint9)
	(can-traverse rover0 waypoint9 waypoint5)
	(can-traverse rover0 waypoint5 waypoint9)
	(can-traverse rover0 waypoint9 waypoint8)
	(can-traverse rover0 waypoint8 waypoint9)
	(can-traverse rover0 waypoint13 waypoint16)
	(can-traverse rover0 waypoint16 waypoint13)
	(can-traverse rover0 waypoint5 waypoint10)
	(can-traverse rover0 waypoint10 waypoint5)
	(= (energy rover1) 50)
	(in rover1 waypoint9)
	(available rover1)
	(store-of rover1store rover1)
	(empty rover1store)
	(equipped-for-rock-analysis rover1)
	(equipped-for-imaging rover1)
	(can-traverse rover1 waypoint9 waypoint0)
	(can-traverse rover1 waypoint0 waypoint9)
	(can-traverse rover1 waypoint9 waypoint3)
	(can-traverse rover1 waypoint3 waypoint9)
	(can-traverse rover1 waypoint9 waypoint4)
	(can-traverse rover1 waypoint4 waypoint9)
	(can-traverse rover1 waypoint9 waypoint7)
	(can-traverse rover1 waypoint7 waypoint9)
	(can-traverse rover1 waypoint9 waypoint10)
	(can-traverse rover1 waypoint10 waypoint9)
	(can-traverse rover1 waypoint9 waypoint12)
	(can-traverse rover1 waypoint12 waypoint9)
	(can-traverse rover1 waypoint9 waypoint14)
	(can-traverse rover1 waypoint14 waypoint9)
	(can-traverse rover1 waypoint9 waypoint18)
	(can-traverse rover1 waypoint18 waypoint9)
	(can-traverse rover1 waypoint9 waypoint19)
	(can-traverse rover1 waypoint19 waypoint9)
	(can-traverse rover1 waypoint0 waypoint2)
	(can-traverse rover1 waypoint2 waypoint0)
	(can-traverse rover1 waypoint0 waypoint13)
	(can-traverse rover1 waypoint13 waypoint0)
	(can-traverse rover1 waypoint0 waypoint16)
	(can-traverse rover1 waypoint16 waypoint0)
	(can-traverse rover1 waypoint3 waypoint6)
	(can-traverse rover1 waypoint6 waypoint3)
	(can-traverse rover1 waypoint4 waypoint11)
	(can-traverse rover1 waypoint11 waypoint4)
	(can-traverse rover1 waypoint7 waypoint5)
	(can-traverse rover1 waypoint5 waypoint7)
	(can-traverse rover1 waypoint10 waypoint8)
	(can-traverse rover1 waypoint8 waypoint10)
	(can-traverse rover1 waypoint12 waypoint1)
	(can-traverse rover1 waypoint1 waypoint12)
	(can-traverse rover1 waypoint14 waypoint15)
	(can-traverse rover1 waypoint15 waypoint14)
	(can-traverse rover1 waypoint19 waypoint17)
	(can-traverse rover1 waypoint17 waypoint19)
	(= (energy rover2) 50)
	(in rover2 waypoint0)
	(available rover2)
	(store-of rover2store rover2)
	(empty rover2store)
	(equipped-for-soil-analysis rover2)
	(equipped-for-imaging rover2)
	(can-traverse rover2 waypoint0 waypoint1)
	(can-traverse rover2 waypoint1 waypoint0)
	(can-traverse rover2 waypoint0 waypoint9)
	(can-traverse rover2 waypoint9 waypoint0)
	(can-traverse rover2 waypoint0 waypoint13)
	(can-traverse rover2 waypoint13 waypoint0)
	(can-traverse rover2 waypoint0 waypoint16)
	(can-traverse rover2 waypoint16 waypoint0)
	(can-traverse rover2 waypoint0 waypoint17)
	(can-traverse rover2 waypoint17 waypoint0)
	(can-traverse rover2 waypoint0 waypoint18)
	(can-traverse rover2 waypoint18 waypoint0)
	(can-traverse rover2 waypoint1 waypoint2)
	(can-traverse rover2 waypoint2 waypoint1)
	(can-traverse rover2 waypoint1 waypoint6)
	(can-traverse rover2 waypoint6 waypoint1)
	(can-traverse rover2 waypoint1 waypoint11)
	(can-traverse rover2 waypoint11 waypoint1)
	(can-traverse rover2 waypoint1 waypoint12)
	(can-traverse rover2 waypoint12 waypoint1)
	(can-traverse rover2 waypoint1 waypoint15)
	(can-traverse rover2 waypoint15 waypoint1)
	(can-traverse rover2 waypoint9 waypoint3)
	(can-traverse rover2 waypoint3 waypoint9)
	(can-traverse rover2 waypoint9 waypoint4)
	(can-traverse rover2 waypoint4 waypoint9)
	(can-traverse rover2 waypoint9 waypoint5)
	(can-traverse rover2 waypoint5 waypoint9)
	(can-traverse rover2 waypoint9 waypoint7)
	(can-traverse rover2 waypoint7 waypoint9)
	(can-traverse rover2 waypoint9 waypoint10)
	(can-traverse rover2 waypoint10 waypoint9)
	(can-traverse rover2 waypoint9 waypoint14)
	(can-traverse rover2 waypoint14 waypoint9)
	(can-traverse rover2 waypoint9 waypoint19)
	(can-traverse rover2 waypoint19 waypoint9)
	(= (energy rover3) 50)
	(in rover3 waypoint18)
	(available rover3)
	(store-of rover3store rover3)
	(empty rover3store)
	(equipped-for-rock-analysis rover3)
	(equipped-for-imaging rover3)
	(can-traverse rover3 waypoint18 waypoint0)
	(can-traverse rover3 waypoint0 waypoint18)
	(can-traverse rover3 waypoint18 waypoint4)
	(can-traverse rover3 waypoint4 waypoint18)
	(can-traverse rover3 waypoint18 waypoint11)
	(can-traverse rover3 waypoint11 waypoint18)
	(can-traverse rover3 waypoint0 waypoint1)
	(can-traverse rover3 waypoint1 waypoint0)
	(can-traverse rover3 waypoint0 waypoint2)
	(can-traverse rover3 waypoint2 waypoint0)
	(can-traverse rover3 waypoint0 waypoint9)
	(can-traverse rover3 waypoint9 waypoint0)
	(can-traverse rover3 waypoint0 waypoint12)
	(can-traverse rover3 waypoint12 waypoint0)
	(can-traverse rover3 waypoint0 waypoint17)
	(can-traverse rover3 waypoint17 waypoint0)
	(can-traverse rover3 waypoint11 waypoint16)
	(can-traverse rover3 waypoint16 waypoint11)
	(can-traverse rover3 waypoint1 waypoint6)
	(can-traverse rover3 waypoint6 waypoint1)
	(can-traverse rover3 waypoint1 waypoint7)
	(can-traverse rover3 waypoint7 waypoint1)
	(can-traverse rover3 waypoint1 waypoint15)
	(can-traverse rover3 waypoint15 waypoint1)
	(can-traverse rover3 waypoint2 waypoint14)
	(can-traverse rover3 waypoint14 waypoint2)
	(can-traverse rover3 waypoint9 waypoint3)
	(can-traverse rover3 waypoint3 waypoint9)
	(can-traverse rover3 waypoint9 waypoint5)
	(can-traverse rover3 waypoint5 waypoint9)
	(can-traverse rover3 waypoint9 waypoint8)
	(can-traverse rover3 waypoint8 waypoint9)
	(can-traverse rover3 waypoint12 waypoint19)
	(can-traverse rover3 waypoint19 waypoint12)
	(can-traverse rover3 waypoint16 waypoint13)
	(can-traverse rover3 waypoint13 waypoint16)
	(can-traverse rover3 waypoint7 waypoint10)
	(can-traverse rover3 waypoint10 waypoint7)
	(= (energy rover4) 50)
	(in rover4 waypoint3)
	(available rover4)
	(store-of rover4store rover4)
	(empty rover4store)
	(equipped-for-soil-analysis rover4)
	(equipped-for-imaging rover4)
	(can-traverse rover4 waypoint3 waypoint6)
	(can-traverse rover4 waypoint6 waypoint3)
	(can-traverse rover4 waypoint3 waypoint7)
	(can-traverse rover4 waypoint7 waypoint3)
	(can-traverse rover4 waypoint3 waypoint9)
	(can-traverse rover4 waypoint9 waypoint3)
	(can-traverse rover4 waypoint3 waypoint10)
	(can-traverse rover4 waypoint10 waypoint3)
	(can-traverse rover4 waypoint3 waypoint11)
	(can-traverse rover4 waypoint11 waypoint3)
	(can-traverse rover4 waypoint3 waypoint13)
	(can-traverse rover4 waypoint13 waypoint3)
	(can-traverse rover4 waypoint3 waypoint15)
	(can-traverse rover4 waypoint15 waypoint3)
	(can-traverse rover4 waypoint6 waypoint5)
	(can-traverse rover4 waypoint5 waypoint6)
	(can-traverse rover4 waypoint6 waypoint12)
	(can-traverse rover4 waypoint12 waypoint6)
	(can-traverse rover4 waypoint6 waypoint14)
	(can-traverse rover4 waypoint14 waypoint6)
	(can-traverse rover4 waypoint9 waypoint0)
	(can-traverse rover4 waypoint0 waypoint9)
	(can-traverse rover4 waypoint9 waypoint4)
	(can-traverse rover4 waypoint4 waypoint9)
	(can-traverse rover4 waypoint9 waypoint8)
	(can-traverse rover4 waypoint8 waypoint9)
	(can-traverse rover4 waypoint9 waypoint19)
	(can-traverse rover4 waypoint19 waypoint9)
	(can-traverse rover4 waypoint10 waypoint16)
	(can-traverse rover4 waypoint16 waypoint10)
	(can-traverse rover4 waypoint11 waypoint17)
	(can-traverse rover4 waypoint17 waypoint11)
	(can-traverse rover4 waypoint11 waypoint18)
	(can-traverse rover4 waypoint18 waypoint11)
	(can-traverse rover4 waypoint15 waypoint1)
	(can-traverse rover4 waypoint1 waypoint15)
	(can-traverse rover4 waypoint14 waypoint2)
	(can-traverse rover4 waypoint2 waypoint14)
	(= (energy rover5) 50)
	(in rover5 waypoint0)
	(available rover5)
	(store-of rover5store rover5)
	(empty rover5store)
	(equipped-for-rock-analysis rover5)
	(equipped-for-imaging rover5)
	(can-traverse rover5 waypoint0 waypoint1)
	(can-traverse rover5 waypoint1 waypoint0)
	(can-traverse rover5 waypoint0 waypoint12)
	(can-traverse rover5 waypoint12 waypoint0)
	(can-traverse rover5 waypoint0 waypoint13)
	(can-traverse rover5 waypoint13 waypoint0)
	(can-traverse rover5 waypoint0 waypoint17)
	(can-traverse rover5 waypoint17 waypoint0)
	(can-traverse rover5 waypoint0 waypoint18)
	(can-traverse rover5 waypoint18 waypoint0)
	(can-traverse rover5 waypoint1 waypoint2)
	(can-traverse rover5 waypoint2 waypoint1)
	(can-traverse rover5 waypoint1 waypoint6)
	(can-traverse rover5 waypoint6 waypoint1)
	(can-traverse rover5 waypoint1 waypoint7)
	(can-traverse rover5 waypoint7 waypoint1)
	(can-traverse rover5 waypoint1 waypoint11)
	(can-traverse rover5 waypoint11 waypoint1)
	(can-traverse rover5 waypoint1 waypoint15)
	(can-traverse rover5 waypoint15 waypoint1)
	(can-traverse rover5 waypoint12 waypoint4)
	(can-traverse rover5 waypoint4 waypoint12)
	(can-traverse rover5 waypoint12 waypoint5)
	(can-traverse rover5 waypoint5 waypoint12)
	(can-traverse rover5 waypoint12 waypoint8)
	(can-traverse rover5 waypoint8 waypoint12)
	(can-traverse rover5 waypoint12 waypoint9)
	(can-traverse rover5 waypoint9 waypoint12)
	(can-traverse rover5 waypoint12 waypoint14)
	(can-traverse rover5 waypoint14 waypoint12)
	(can-traverse rover5 waypoint12 waypoint19)
	(can-traverse rover5 waypoint19 waypoint12)
	(can-traverse rover5 waypoint13 waypoint16)
	(can-traverse rover5 waypoint16 waypoint13)
	(can-traverse rover5 waypoint7 waypoint3)
	(can-traverse rover5 waypoint3 waypoint7)
	(can-traverse rover5 waypoint7 waypoint10)
	(can-traverse rover5 waypoint10 waypoint7)
	(on-board camera0 rover1)
	(calibration-target camera0 objective4)
	(supports camera0 high-res)
	(on-board camera1 rover2)
	(calibration-target camera1 objective6)
	(supports camera1 colour)
	(supports camera1 low-res)
	(on-board camera2 rover4)
	(calibration-target camera2 objective0)
	(supports camera2 colour)
	(supports camera2 high-res)
	(on-board camera3 rover3)
	(calibration-target camera3 objective6)
	(supports camera3 colour)
	(on-board camera4 rover3)
	(calibration-target camera4 objective4)
	(supports camera4 high-res)
	(supports camera4 low-res)
	(on-board camera5 rover0)
	(calibration-target camera5 objective2)
	(supports camera5 colour)
	(on-board camera6 rover5)
	(calibration-target camera6 objective6)
	(supports camera6 high-res)
	(supports camera6 low-res)
	(visible-from objective0 waypoint0)
	(visible-from objective0 waypoint1)
	(visible-from objective0 waypoint2)
	(visible-from objective0 waypoint3)
	(visible-from objective0 waypoint4)
	(visible-from objective0 waypoint5)
	(visible-from objective0 waypoint6)
	(visible-from objective0 waypoint7)
	(visible-from objective0 waypoint8)
	(visible-from objective0 waypoint9)
	(visible-from objective0 waypoint10)
	(visible-from objective1 waypoint0)
	(visible-from objective1 waypoint1)
	(visible-from objective1 waypoint2)
	(visible-from objective1 waypoint3)
	(visible-from objective1 waypoint4)
	(visible-from objective1 waypoint5)
	(visible-from objective1 waypoint6)
	(visible-from objective1 waypoint7)
	(visible-from objective1 waypoint8)
	(visible-from objective1 waypoint9)
	(visible-from objective1 waypoint10)
	(visible-from objective1 waypoint11)
	(visible-from objective1 waypoint12)
	(visible-from objective2 waypoint0)
	(visible-from objective2 waypoint1)
	(visible-from objective2 waypoint2)
	(visible-from objective2 waypoint3)
	(visible-from objective2 waypoint4)
	(visible-from objective2 waypoint5)
	(visible-from objective2 waypoint6)
	(visible-from objective2 waypoint7)
	(visible-from objective2 waypoint8)
	(visible-from objective2 waypoint9)
	(visible-from objective2 waypoint10)
	(visible-from objective2 waypoint11)
	(visible-from objective2 waypoint12)
	(visible-from objective2 waypoint13)
	(visible-from objective2 waypoint14)
	(visible-from objective3 waypoint0)
	(visible-from objective3 waypoint1)
	(visible-from objective3 waypoint2)
	(visible-from objective3 waypoint3)
	(visible-from objective3 waypoint4)
	(visible-from objective3 waypoint5)
	(visible-from objective3 waypoint6)
	(visible-from objective3 waypoint7)
	(visible-from objective3 waypoint8)
	(visible-from objective3 waypoint9)
	(visible-from objective3 waypoint10)
	(visible-from objective3 waypoint11)
	(visible-from objective3 waypoint12)
	(visible-from objective3 waypoint13)
	(visible-from objective3 waypoint14)
	(visible-from objective3 waypoint15)
	(visible-from objective3 waypoint16)
	(visible-from objective3 waypoint17)
	(visible-from objective3 waypoint18)
	(visible-from objective3 waypoint19)
	(visible-from objective4 waypoint0)
	(visible-from objective4 waypoint1)
	(visible-from objective4 waypoint2)
	(visible-from objective4 waypoint3)
	(visible-from objective4 waypoint4)
	(visible-from objective4 waypoint5)
	(visible-from objective4 waypoint6)
	(visible-from objective4 waypoint7)
	(visible-from objective4 waypoint8)
	(visible-from objective4 waypoint9)
	(visible-from objective4 waypoint10)
	(visible-from objective4 waypoint11)
	(visible-from objective4 waypoint12)
	(visible-from objective4 waypoint13)
	(visible-from objective4 waypoint14)
	(visible-from objective4 waypoint15)
	(visible-from objective5 waypoint0)
	(visible-from objective5 waypoint1)
	(visible-from objective5 waypoint2)
	(visible-from objective6 waypoint0)
	(visible-from objective6 waypoint1)
	(visible-from objective6 waypoint2)
	(visible-from objective6 waypoint3)
	(visible-from objective6 waypoint4)
	(visible-from objective6 waypoint5)
	(visible-from objective6 waypoint6)
	(visible-from objective6 waypoint7)
	(visible-from objective6 waypoint8)
	(visible-from objective6 waypoint9)
	(visible-from objective6 waypoint10)
)

(:goal (and
(communicated-soil-data waypoint14)
(communicated-soil-data waypoint0)
(communicated-rock-data waypoint4)
(communicated-rock-data waypoint7)
(communicated-rock-data waypoint2)
(communicated-rock-data waypoint5)
(communicated-rock-data waypoint6)
(communicated-image-data objective5 colour)
(communicated-image-data objective3 low-res)
(communicated-image-data objective2 colour)
(communicated-image-data objective4 high-res)
	)
)

(:metric minimize (recharges))
)
