(define (problem roverprob4135) (:domain rover)
(:objects
	general - lander
	colour high-res low-res - mode
	rover0 rover1 rover2 rover3 - agent
	rover0store rover1store rover2store rover3store - store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 - waypoint
	camera0 camera1 camera2 camera3 - camera
	objective0 objective1 objective2 objective3 objective4 - objective
	)
(:init
	(visible waypoint0 waypoint3)
	(visible waypoint3 waypoint0)
	(visible waypoint0 waypoint4)
	(visible waypoint4 waypoint0)
	(visible waypoint1 waypoint0)
	(visible waypoint0 waypoint1)
	(visible waypoint1 waypoint5)
	(visible waypoint5 waypoint1)
	(visible waypoint1 waypoint6)
	(visible waypoint6 waypoint1)
	(visible waypoint1 waypoint7)
	(visible waypoint7 waypoint1)
	(visible waypoint1 waypoint8)
	(visible waypoint8 waypoint1)
	(visible waypoint1 waypoint10)
	(visible waypoint10 waypoint1)
	(visible waypoint2 waypoint0)
	(visible waypoint0 waypoint2)
	(visible waypoint2 waypoint1)
	(visible waypoint1 waypoint2)
	(visible waypoint2 waypoint6)
	(visible waypoint6 waypoint2)
	(visible waypoint3 waypoint1)
	(visible waypoint1 waypoint3)
	(visible waypoint3 waypoint6)
	(visible waypoint6 waypoint3)
	(visible waypoint3 waypoint9)
	(visible waypoint9 waypoint3)
	(visible waypoint3 waypoint10)
	(visible waypoint10 waypoint3)
	(visible waypoint4 waypoint1)
	(visible waypoint1 waypoint4)
	(visible waypoint4 waypoint2)
	(visible waypoint2 waypoint4)
	(visible waypoint4 waypoint5)
	(visible waypoint5 waypoint4)
	(visible waypoint4 waypoint6)
	(visible waypoint6 waypoint4)
	(visible waypoint4 waypoint8)
	(visible waypoint8 waypoint4)
	(visible waypoint5 waypoint2)
	(visible waypoint2 waypoint5)
	(visible waypoint5 waypoint6)
	(visible waypoint6 waypoint5)
	(visible waypoint7 waypoint0)
	(visible waypoint0 waypoint7)
	(visible waypoint7 waypoint3)
	(visible waypoint3 waypoint7)
	(visible waypoint7 waypoint5)
	(visible waypoint5 waypoint7)
	(visible waypoint7 waypoint9)
	(visible waypoint9 waypoint7)
	(visible waypoint7 waypoint10)
	(visible waypoint10 waypoint7)
	(visible waypoint8 waypoint0)
	(visible waypoint0 waypoint8)
	(visible waypoint8 waypoint3)
	(visible waypoint3 waypoint8)
	(visible waypoint9 waypoint4)
	(visible waypoint4 waypoint9)
	(visible waypoint9 waypoint6)
	(visible waypoint6 waypoint9)
	(visible waypoint9 waypoint8)
	(visible waypoint8 waypoint9)
	(visible waypoint10 waypoint4)
	(visible waypoint4 waypoint10)
	(visible waypoint10 waypoint5)
	(visible waypoint5 waypoint10)
	(visible waypoint10 waypoint6)
	(visible waypoint6 waypoint10)
	(visible waypoint10 waypoint8)
	(visible waypoint8 waypoint10)
	(= (recharges) 0)
	(at-soil-sample waypoint0)
	(in-sun waypoint0)
	(at-rock-sample waypoint1)
	(at-soil-sample waypoint2)
	(at-rock-sample waypoint2)
	(in-sun waypoint2)
	(in-sun waypoint3)
	(at-soil-sample waypoint4)
	(at-soil-sample waypoint5)
	(in-sun waypoint5)
	(at-soil-sample waypoint7)
	(at-soil-sample waypoint8)
	(at-rock-sample waypoint8)
	(at-rock-sample waypoint9)
	(in-sun waypoint9)
	(at-soil-sample waypoint10)
	(at-rock-sample waypoint10)
	(in-sun waypoint10)
	(at-lander general waypoint9)
	(channel-free general)
	(= (energy rover0) 50)
	(in rover0 waypoint4)
	(available rover0)
	(store-of rover0store rover0)
	(empty rover0store)
	(equipped-for-soil-analysis rover0)
	(equipped-for-imaging rover0)
	(can-traverse rover0 waypoint4 waypoint0)
	(can-traverse rover0 waypoint0 waypoint4)
	(can-traverse rover0 waypoint4 waypoint1)
	(can-traverse rover0 waypoint1 waypoint4)
	(can-traverse rover0 waypoint4 waypoint2)
	(can-traverse rover0 waypoint2 waypoint4)
	(can-traverse rover0 waypoint4 waypoint5)
	(can-traverse rover0 waypoint5 waypoint4)
	(can-traverse rover0 waypoint4 waypoint8)
	(can-traverse rover0 waypoint8 waypoint4)
	(can-traverse rover0 waypoint4 waypoint9)
	(can-traverse rover0 waypoint9 waypoint4)
	(can-traverse rover0 waypoint4 waypoint10)
	(can-traverse rover0 waypoint10 waypoint4)
	(can-traverse rover0 waypoint0 waypoint3)
	(can-traverse rover0 waypoint3 waypoint0)
	(can-traverse rover0 waypoint0 waypoint7)
	(can-traverse rover0 waypoint7 waypoint0)
	(can-traverse rover0 waypoint1 waypoint6)
	(can-traverse rover0 waypoint6 waypoint1)
	(= (energy rover1) 50)
	(in rover1 waypoint6)
	(available rover1)
	(store-of rover1store rover1)
	(empty rover1store)
	(equipped-for-imaging rover1)
	(can-traverse rover1 waypoint6 waypoint1)
	(can-traverse rover1 waypoint1 waypoint6)
	(can-traverse rover1 waypoint6 waypoint2)
	(can-traverse rover1 waypoint2 waypoint6)
	(can-traverse rover1 waypoint6 waypoint3)
	(can-traverse rover1 waypoint3 waypoint6)
	(can-traverse rover1 waypoint6 waypoint4)
	(can-traverse rover1 waypoint4 waypoint6)
	(can-traverse rover1 waypoint6 waypoint5)
	(can-traverse rover1 waypoint5 waypoint6)
	(can-traverse rover1 waypoint6 waypoint10)
	(can-traverse rover1 waypoint10 waypoint6)
	(can-traverse rover1 waypoint1 waypoint0)
	(can-traverse rover1 waypoint0 waypoint1)
	(can-traverse rover1 waypoint1 waypoint7)
	(can-traverse rover1 waypoint7 waypoint1)
	(can-traverse rover1 waypoint1 waypoint8)
	(can-traverse rover1 waypoint8 waypoint1)
	(can-traverse rover1 waypoint3 waypoint9)
	(can-traverse rover1 waypoint9 waypoint3)
	(= (energy rover2) 50)
	(in rover2 waypoint6)
	(available rover2)
	(store-of rover2store rover2)
	(empty rover2store)
	(equipped-for-soil-analysis rover2)
	(can-traverse rover2 waypoint6 waypoint1)
	(can-traverse rover2 waypoint1 waypoint6)
	(can-traverse rover2 waypoint6 waypoint4)
	(can-traverse rover2 waypoint4 waypoint6)
	(can-traverse rover2 waypoint6 waypoint5)
	(can-traverse rover2 waypoint5 waypoint6)
	(can-traverse rover2 waypoint6 waypoint9)
	(can-traverse rover2 waypoint9 waypoint6)
	(can-traverse rover2 waypoint6 waypoint10)
	(can-traverse rover2 waypoint10 waypoint6)
	(can-traverse rover2 waypoint1 waypoint0)
	(can-traverse rover2 waypoint0 waypoint1)
	(can-traverse rover2 waypoint1 waypoint7)
	(can-traverse rover2 waypoint7 waypoint1)
	(can-traverse rover2 waypoint4 waypoint2)
	(can-traverse rover2 waypoint2 waypoint4)
	(can-traverse rover2 waypoint9 waypoint3)
	(can-traverse rover2 waypoint3 waypoint9)
	(can-traverse rover2 waypoint9 waypoint8)
	(can-traverse rover2 waypoint8 waypoint9)
	(= (energy rover3) 50)
	(in rover3 waypoint4)
	(available rover3)
	(store-of rover3store rover3)
	(empty rover3store)
	(equipped-for-rock-analysis rover3)
	(equipped-for-imaging rover3)
	(can-traverse rover3 waypoint4 waypoint0)
	(can-traverse rover3 waypoint0 waypoint4)
	(can-traverse rover3 waypoint4 waypoint1)
	(can-traverse rover3 waypoint1 waypoint4)
	(can-traverse rover3 waypoint4 waypoint2)
	(can-traverse rover3 waypoint2 waypoint4)
	(can-traverse rover3 waypoint4 waypoint5)
	(can-traverse rover3 waypoint5 waypoint4)
	(can-traverse rover3 waypoint4 waypoint6)
	(can-traverse rover3 waypoint6 waypoint4)
	(can-traverse rover3 waypoint4 waypoint8)
	(can-traverse rover3 waypoint8 waypoint4)
	(can-traverse rover3 waypoint4 waypoint9)
	(can-traverse rover3 waypoint9 waypoint4)
	(can-traverse rover3 waypoint0 waypoint7)
	(can-traverse rover3 waypoint7 waypoint0)
	(can-traverse rover3 waypoint1 waypoint3)
	(can-traverse rover3 waypoint3 waypoint1)
	(can-traverse rover3 waypoint1 waypoint10)
	(can-traverse rover3 waypoint10 waypoint1)
	(on-board camera0 rover3)
	(calibration-target camera0 objective2)
	(supports camera0 low-res)
	(on-board camera1 rover0)
	(calibration-target camera1 objective4)
	(supports camera1 colour)
	(supports camera1 high-res)
	(supports camera1 low-res)
	(on-board camera2 rover1)
	(calibration-target camera2 objective4)
	(supports camera2 high-res)
	(supports camera2 low-res)
	(on-board camera3 rover1)
	(calibration-target camera3 objective3)
	(supports camera3 colour)
	(supports camera3 high-res)
	(supports camera3 low-res)
	(visible-from objective0 waypoint0)
	(visible-from objective0 waypoint1)
	(visible-from objective0 waypoint2)
	(visible-from objective0 waypoint3)
	(visible-from objective0 waypoint4)
	(visible-from objective0 waypoint5)
	(visible-from objective0 waypoint6)
	(visible-from objective0 waypoint7)
	(visible-from objective0 waypoint8)
	(visible-from objective0 waypoint9)
	(visible-from objective0 waypoint10)
	(visible-from objective1 waypoint0)
	(visible-from objective1 waypoint1)
	(visible-from objective1 waypoint2)
	(visible-from objective1 waypoint3)
	(visible-from objective1 waypoint4)
	(visible-from objective1 waypoint5)
	(visible-from objective1 waypoint6)
	(visible-from objective1 waypoint7)
	(visible-from objective1 waypoint8)
	(visible-from objective1 waypoint9)
	(visible-from objective2 waypoint0)
	(visible-from objective2 waypoint1)
	(visible-from objective2 waypoint2)
	(visible-from objective3 waypoint0)
	(visible-from objective3 waypoint1)
	(visible-from objective3 waypoint2)
	(visible-from objective3 waypoint3)
	(visible-from objective3 waypoint4)
	(visible-from objective4 waypoint0)
	(visible-from objective4 waypoint1)
	(visible-from objective4 waypoint2)
	(visible-from objective4 waypoint3)
	(visible-from objective4 waypoint4)
	(visible-from objective4 waypoint5)
	(visible-from objective4 waypoint6)
	(visible-from objective4 waypoint7)
	(visible-from objective4 waypoint8)
	(visible-from objective4 waypoint9)
)

(:goal (and
(communicated-soil-data waypoint5)
(communicated-soil-data waypoint2)
(communicated-soil-data waypoint8)
(communicated-soil-data waypoint10)
(communicated-soil-data waypoint0)
(communicated-rock-data waypoint2)
(communicated-rock-data waypoint1)
(communicated-rock-data waypoint8)
(communicated-image-data objective1 low-res)
(communicated-image-data objective1 high-res)
	)
)

(:metric minimize (recharges))
)
