(define (problem roverprob5624) (:domain rover)
(:objects
	general - lander
	colour high-res low-res - mode
	rover0 rover1 rover2 rover3 rover4 rover5 - agent
	rover0store rover1store rover2store rover3store rover4store rover5store - store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 - waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 - camera
	objective0 objective1 objective2 objective3 objective4 objective5 - objective
	)
(:init
	(visible waypoint1 waypoint0)
	(visible waypoint0 waypoint1)
	(visible waypoint1 waypoint8)
	(visible waypoint8 waypoint1)
	(visible waypoint1 waypoint11)
	(visible waypoint11 waypoint1)
	(visible waypoint1 waypoint14)
	(visible waypoint14 waypoint1)
	(visible waypoint2 waypoint6)
	(visible waypoint6 waypoint2)
	(visible waypoint2 waypoint9)
	(visible waypoint9 waypoint2)
	(visible waypoint3 waypoint0)
	(visible waypoint0 waypoint3)
	(visible waypoint3 waypoint2)
	(visible waypoint2 waypoint3)
	(visible waypoint3 waypoint6)
	(visible waypoint6 waypoint3)
	(visible waypoint3 waypoint7)
	(visible waypoint7 waypoint3)
	(visible waypoint3 waypoint11)
	(visible waypoint11 waypoint3)
	(visible waypoint3 waypoint13)
	(visible waypoint13 waypoint3)
	(visible waypoint4 waypoint1)
	(visible waypoint1 waypoint4)
	(visible waypoint4 waypoint2)
	(visible waypoint2 waypoint4)
	(visible waypoint4 waypoint10)
	(visible waypoint10 waypoint4)
	(visible waypoint4 waypoint14)
	(visible waypoint14 waypoint4)
	(visible waypoint5 waypoint1)
	(visible waypoint1 waypoint5)
	(visible waypoint5 waypoint2)
	(visible waypoint2 waypoint5)
	(visible waypoint5 waypoint3)
	(visible waypoint3 waypoint5)
	(visible waypoint5 waypoint8)
	(visible waypoint8 waypoint5)
	(visible waypoint5 waypoint14)
	(visible waypoint14 waypoint5)
	(visible waypoint6 waypoint0)
	(visible waypoint0 waypoint6)
	(visible waypoint6 waypoint4)
	(visible waypoint4 waypoint6)
	(visible waypoint6 waypoint5)
	(visible waypoint5 waypoint6)
	(visible waypoint6 waypoint7)
	(visible waypoint7 waypoint6)
	(visible waypoint6 waypoint10)
	(visible waypoint10 waypoint6)
	(visible waypoint6 waypoint12)
	(visible waypoint12 waypoint6)
	(visible waypoint6 waypoint13)
	(visible waypoint13 waypoint6)
	(visible waypoint7 waypoint8)
	(visible waypoint8 waypoint7)
	(visible waypoint7 waypoint9)
	(visible waypoint9 waypoint7)
	(visible waypoint8 waypoint2)
	(visible waypoint2 waypoint8)
	(visible waypoint8 waypoint3)
	(visible waypoint3 waypoint8)
	(visible waypoint8 waypoint10)
	(visible waypoint10 waypoint8)
	(visible waypoint9 waypoint8)
	(visible waypoint8 waypoint9)
	(visible waypoint10 waypoint0)
	(visible waypoint0 waypoint10)
	(visible waypoint10 waypoint3)
	(visible waypoint3 waypoint10)
	(visible waypoint11 waypoint2)
	(visible waypoint2 waypoint11)
	(visible waypoint11 waypoint4)
	(visible waypoint4 waypoint11)
	(visible waypoint11 waypoint8)
	(visible waypoint8 waypoint11)
	(visible waypoint11 waypoint9)
	(visible waypoint9 waypoint11)
	(visible waypoint11 waypoint10)
	(visible waypoint10 waypoint11)
	(visible waypoint12 waypoint0)
	(visible waypoint0 waypoint12)
	(visible waypoint12 waypoint1)
	(visible waypoint1 waypoint12)
	(visible waypoint12 waypoint5)
	(visible waypoint5 waypoint12)
	(visible waypoint12 waypoint7)
	(visible waypoint7 waypoint12)
	(visible waypoint13 waypoint0)
	(visible waypoint0 waypoint13)
	(visible waypoint13 waypoint5)
	(visible waypoint5 waypoint13)
	(visible waypoint13 waypoint14)
	(visible waypoint14 waypoint13)
	(visible waypoint14 waypoint2)
	(visible waypoint2 waypoint14)
	(visible waypoint14 waypoint3)
	(visible waypoint3 waypoint14)
	(visible waypoint14 waypoint9)
	(visible waypoint9 waypoint14)
	(visible waypoint14 waypoint10)
	(visible waypoint10 waypoint14)
	(= (recharges) 0)
	(at-soil-sample waypoint0)
	(in-sun waypoint0)
	(at-rock-sample waypoint1)
	(at-soil-sample waypoint2)
	(at-rock-sample waypoint2)
	(at-soil-sample waypoint3)
	(at-rock-sample waypoint3)
	(in-sun waypoint3)
	(at-soil-sample waypoint4)
	(at-rock-sample waypoint4)
	(at-soil-sample waypoint5)
	(at-rock-sample waypoint5)
	(at-rock-sample waypoint6)
	(at-rock-sample waypoint7)
	(in-sun waypoint7)
	(at-soil-sample waypoint9)
	(at-rock-sample waypoint9)
	(at-rock-sample waypoint10)
	(at-rock-sample waypoint11)
	(at-rock-sample waypoint12)
	(at-soil-sample waypoint13)
	(at-rock-sample waypoint13)
	(at-soil-sample waypoint14)
	(at-rock-sample waypoint14)
	(at-lander general waypoint13)
	(channel-free general)
	(= (energy rover0) 50)
	(in rover0 waypoint12)
	(available rover0)
	(store-of rover0store rover0)
	(empty rover0store)
	(equipped-for-rock-analysis rover0)
	(can-traverse rover0 waypoint12 waypoint0)
	(can-traverse rover0 waypoint0 waypoint12)
	(can-traverse rover0 waypoint12 waypoint1)
	(can-traverse rover0 waypoint1 waypoint12)
	(can-traverse rover0 waypoint12 waypoint6)
	(can-traverse rover0 waypoint6 waypoint12)
	(can-traverse rover0 waypoint12 waypoint7)
	(can-traverse rover0 waypoint7 waypoint12)
	(can-traverse rover0 waypoint0 waypoint3)
	(can-traverse rover0 waypoint3 waypoint0)
	(can-traverse rover0 waypoint1 waypoint4)
	(can-traverse rover0 waypoint4 waypoint1)
	(can-traverse rover0 waypoint1 waypoint5)
	(can-traverse rover0 waypoint5 waypoint1)
	(can-traverse rover0 waypoint1 waypoint8)
	(can-traverse rover0 waypoint8 waypoint1)
	(can-traverse rover0 waypoint1 waypoint11)
	(can-traverse rover0 waypoint11 waypoint1)
	(can-traverse rover0 waypoint6 waypoint13)
	(can-traverse rover0 waypoint13 waypoint6)
	(can-traverse rover0 waypoint7 waypoint9)
	(can-traverse rover0 waypoint9 waypoint7)
	(= (energy rover1) 50)
	(in rover1 waypoint12)
	(available rover1)
	(store-of rover1store rover1)
	(empty rover1store)
	(equipped-for-imaging rover1)
	(can-traverse rover1 waypoint12 waypoint0)
	(can-traverse rover1 waypoint0 waypoint12)
	(can-traverse rover1 waypoint12 waypoint1)
	(can-traverse rover1 waypoint1 waypoint12)
	(can-traverse rover1 waypoint12 waypoint5)
	(can-traverse rover1 waypoint5 waypoint12)
	(can-traverse rover1 waypoint12 waypoint6)
	(can-traverse rover1 waypoint6 waypoint12)
	(can-traverse rover1 waypoint0 waypoint3)
	(can-traverse rover1 waypoint3 waypoint0)
	(can-traverse rover1 waypoint0 waypoint13)
	(can-traverse rover1 waypoint13 waypoint0)
	(can-traverse rover1 waypoint1 waypoint11)
	(can-traverse rover1 waypoint11 waypoint1)
	(can-traverse rover1 waypoint1 waypoint14)
	(can-traverse rover1 waypoint14 waypoint1)
	(can-traverse rover1 waypoint5 waypoint2)
	(can-traverse rover1 waypoint2 waypoint5)
	(can-traverse rover1 waypoint5 waypoint8)
	(can-traverse rover1 waypoint8 waypoint5)
	(can-traverse rover1 waypoint6 waypoint4)
	(can-traverse rover1 waypoint4 waypoint6)
	(can-traverse rover1 waypoint6 waypoint7)
	(can-traverse rover1 waypoint7 waypoint6)
	(can-traverse rover1 waypoint6 waypoint10)
	(can-traverse rover1 waypoint10 waypoint6)
	(can-traverse rover1 waypoint11 waypoint9)
	(can-traverse rover1 waypoint9 waypoint11)
	(= (energy rover2) 50)
	(in rover2 waypoint5)
	(available rover2)
	(store-of rover2store rover2)
	(empty rover2store)
	(equipped-for-imaging rover2)
	(can-traverse rover2 waypoint5 waypoint1)
	(can-traverse rover2 waypoint1 waypoint5)
	(can-traverse rover2 waypoint5 waypoint2)
	(can-traverse rover2 waypoint2 waypoint5)
	(can-traverse rover2 waypoint5 waypoint6)
	(can-traverse rover2 waypoint6 waypoint5)
	(can-traverse rover2 waypoint5 waypoint8)
	(can-traverse rover2 waypoint8 waypoint5)
	(can-traverse rover2 waypoint5 waypoint13)
	(can-traverse rover2 waypoint13 waypoint5)
	(can-traverse rover2 waypoint5 waypoint14)
	(can-traverse rover2 waypoint14 waypoint5)
	(can-traverse rover2 waypoint1 waypoint0)
	(can-traverse rover2 waypoint0 waypoint1)
	(can-traverse rover2 waypoint1 waypoint4)
	(can-traverse rover2 waypoint4 waypoint1)
	(can-traverse rover2 waypoint2 waypoint3)
	(can-traverse rover2 waypoint3 waypoint2)
	(can-traverse rover2 waypoint2 waypoint9)
	(can-traverse rover2 waypoint9 waypoint2)
	(can-traverse rover2 waypoint2 waypoint11)
	(can-traverse rover2 waypoint11 waypoint2)
	(can-traverse rover2 waypoint6 waypoint7)
	(can-traverse rover2 waypoint7 waypoint6)
	(can-traverse rover2 waypoint6 waypoint12)
	(can-traverse rover2 waypoint12 waypoint6)
	(can-traverse rover2 waypoint8 waypoint10)
	(can-traverse rover2 waypoint10 waypoint8)
	(= (energy rover3) 50)
	(in rover3 waypoint13)
	(available rover3)
	(store-of rover3store rover3)
	(empty rover3store)
	(equipped-for-soil-analysis rover3)
	(equipped-for-imaging rover3)
	(can-traverse rover3 waypoint13 waypoint0)
	(can-traverse rover3 waypoint0 waypoint13)
	(can-traverse rover3 waypoint13 waypoint3)
	(can-traverse rover3 waypoint3 waypoint13)
	(can-traverse rover3 waypoint13 waypoint5)
	(can-traverse rover3 waypoint5 waypoint13)
	(can-traverse rover3 waypoint13 waypoint6)
	(can-traverse rover3 waypoint6 waypoint13)
	(can-traverse rover3 waypoint0 waypoint1)
	(can-traverse rover3 waypoint1 waypoint0)
	(can-traverse rover3 waypoint0 waypoint10)
	(can-traverse rover3 waypoint10 waypoint0)
	(can-traverse rover3 waypoint3 waypoint7)
	(can-traverse rover3 waypoint7 waypoint3)
	(can-traverse rover3 waypoint3 waypoint8)
	(can-traverse rover3 waypoint8 waypoint3)
	(can-traverse rover3 waypoint3 waypoint11)
	(can-traverse rover3 waypoint11 waypoint3)
	(can-traverse rover3 waypoint5 waypoint2)
	(can-traverse rover3 waypoint2 waypoint5)
	(can-traverse rover3 waypoint5 waypoint12)
	(can-traverse rover3 waypoint12 waypoint5)
	(can-traverse rover3 waypoint5 waypoint14)
	(can-traverse rover3 waypoint14 waypoint5)
	(can-traverse rover3 waypoint1 waypoint4)
	(can-traverse rover3 waypoint4 waypoint1)
	(= (energy rover4) 50)
	(in rover4 waypoint1)
	(available rover4)
	(store-of rover4store rover4)
	(empty rover4store)
	(equipped-for-rock-analysis rover4)
	(equipped-for-imaging rover4)
	(can-traverse rover4 waypoint1 waypoint0)
	(can-traverse rover4 waypoint0 waypoint1)
	(can-traverse rover4 waypoint1 waypoint4)
	(can-traverse rover4 waypoint4 waypoint1)
	(can-traverse rover4 waypoint1 waypoint5)
	(can-traverse rover4 waypoint5 waypoint1)
	(can-traverse rover4 waypoint1 waypoint8)
	(can-traverse rover4 waypoint8 waypoint1)
	(can-traverse rover4 waypoint1 waypoint12)
	(can-traverse rover4 waypoint12 waypoint1)
	(can-traverse rover4 waypoint1 waypoint14)
	(can-traverse rover4 waypoint14 waypoint1)
	(can-traverse rover4 waypoint0 waypoint3)
	(can-traverse rover4 waypoint3 waypoint0)
	(can-traverse rover4 waypoint0 waypoint6)
	(can-traverse rover4 waypoint6 waypoint0)
	(can-traverse rover4 waypoint0 waypoint10)
	(can-traverse rover4 waypoint10 waypoint0)
	(can-traverse rover4 waypoint0 waypoint13)
	(can-traverse rover4 waypoint13 waypoint0)
	(can-traverse rover4 waypoint4 waypoint2)
	(can-traverse rover4 waypoint2 waypoint4)
	(can-traverse rover4 waypoint4 waypoint11)
	(can-traverse rover4 waypoint11 waypoint4)
	(can-traverse rover4 waypoint8 waypoint7)
	(can-traverse rover4 waypoint7 waypoint8)
	(can-traverse rover4 waypoint14 waypoint9)
	(can-traverse rover4 waypoint9 waypoint14)
	(= (energy rover5) 50)
	(in rover5 waypoint8)
	(available rover5)
	(store-of rover5store rover5)
	(empty rover5store)
	(equipped-for-rock-analysis rover5)
	(equipped-for-imaging rover5)
	(can-traverse rover5 waypoint8 waypoint1)
	(can-traverse rover5 waypoint1 waypoint8)
	(can-traverse rover5 waypoint8 waypoint3)
	(can-traverse rover5 waypoint3 waypoint8)
	(can-traverse rover5 waypoint8 waypoint5)
	(can-traverse rover5 waypoint5 waypoint8)
	(can-traverse rover5 waypoint8 waypoint7)
	(can-traverse rover5 waypoint7 waypoint8)
	(can-traverse rover5 waypoint8 waypoint9)
	(can-traverse rover5 waypoint9 waypoint8)
	(can-traverse rover5 waypoint8 waypoint10)
	(can-traverse rover5 waypoint10 waypoint8)
	(can-traverse rover5 waypoint8 waypoint11)
	(can-traverse rover5 waypoint11 waypoint8)
	(can-traverse rover5 waypoint1 waypoint4)
	(can-traverse rover5 waypoint4 waypoint1)
	(can-traverse rover5 waypoint1 waypoint12)
	(can-traverse rover5 waypoint12 waypoint1)
	(can-traverse rover5 waypoint1 waypoint14)
	(can-traverse rover5 waypoint14 waypoint1)
	(can-traverse rover5 waypoint3 waypoint0)
	(can-traverse rover5 waypoint0 waypoint3)
	(can-traverse rover5 waypoint3 waypoint6)
	(can-traverse rover5 waypoint6 waypoint3)
	(can-traverse rover5 waypoint5 waypoint2)
	(can-traverse rover5 waypoint2 waypoint5)
	(can-traverse rover5 waypoint5 waypoint13)
	(can-traverse rover5 waypoint13 waypoint5)
	(on-board camera0 rover4)
	(calibration-target camera0 objective2)
	(supports camera0 high-res)
	(supports camera0 low-res)
	(on-board camera1 rover3)
	(calibration-target camera1 objective2)
	(supports camera1 colour)
	(on-board camera2 rover5)
	(calibration-target camera2 objective1)
	(supports camera2 colour)
	(supports camera2 high-res)
	(on-board camera3 rover3)
	(calibration-target camera3 objective5)
	(supports camera3 colour)
	(on-board camera4 rover5)
	(calibration-target camera4 objective3)
	(supports camera4 colour)
	(supports camera4 high-res)
	(supports camera4 low-res)
	(on-board camera5 rover1)
	(calibration-target camera5 objective0)
	(supports camera5 low-res)
	(on-board camera6 rover2)
	(calibration-target camera6 objective5)
	(supports camera6 colour)
	(supports camera6 high-res)
	(visible-from objective0 waypoint0)
	(visible-from objective0 waypoint1)
	(visible-from objective0 waypoint2)
	(visible-from objective0 waypoint3)
	(visible-from objective1 waypoint0)
	(visible-from objective1 waypoint1)
	(visible-from objective2 waypoint0)
	(visible-from objective2 waypoint1)
	(visible-from objective2 waypoint2)
	(visible-from objective2 waypoint3)
	(visible-from objective2 waypoint4)
	(visible-from objective2 waypoint5)
	(visible-from objective2 waypoint6)
	(visible-from objective2 waypoint7)
	(visible-from objective2 waypoint8)
	(visible-from objective2 waypoint9)
	(visible-from objective2 waypoint10)
	(visible-from objective2 waypoint11)
	(visible-from objective2 waypoint12)
	(visible-from objective2 waypoint13)
	(visible-from objective2 waypoint14)
	(visible-from objective3 waypoint0)
	(visible-from objective3 waypoint1)
	(visible-from objective3 waypoint2)
	(visible-from objective3 waypoint3)
	(visible-from objective3 waypoint4)
	(visible-from objective3 waypoint5)
	(visible-from objective4 waypoint0)
	(visible-from objective4 waypoint1)
	(visible-from objective4 waypoint2)
	(visible-from objective4 waypoint3)
	(visible-from objective4 waypoint4)
	(visible-from objective4 waypoint5)
	(visible-from objective4 waypoint6)
	(visible-from objective4 waypoint7)
	(visible-from objective4 waypoint8)
	(visible-from objective4 waypoint9)
	(visible-from objective4 waypoint10)
	(visible-from objective4 waypoint11)
	(visible-from objective4 waypoint12)
	(visible-from objective5 waypoint0)
	(visible-from objective5 waypoint1)
)

(:goal (and
(communicated-soil-data waypoint14)
(communicated-soil-data waypoint5)
(communicated-soil-data waypoint2)
(communicated-soil-data waypoint3)
(communicated-rock-data waypoint3)
(communicated-rock-data waypoint5)
(communicated-rock-data waypoint12)
(communicated-rock-data waypoint9)
(communicated-image-data objective2 colour)
(communicated-image-data objective2 low-res)
(communicated-image-data objective3 colour)
(communicated-image-data objective5 colour)
(communicated-image-data objective4 colour)
	)
)

(:metric minimize (recharges))
)
