(define (problem roverprob1423) (:domain rover)
(:objects
	general - lander
	colour high-res low-res - mode
	rover0 rover1 rover2 rover3 - agent
	rover0store rover1store rover2store rover3store - store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 - waypoint
	camera0 camera1 camera2 camera3 - camera
	objective0 objective1 objective2 - objective
	)
(:init
	(visible waypoint0 waypoint1)
	(visible waypoint1 waypoint0)
	(visible waypoint0 waypoint3)
	(visible waypoint3 waypoint0)
	(visible waypoint1 waypoint5)
	(visible waypoint5 waypoint1)
	(visible waypoint2 waypoint0)
	(visible waypoint0 waypoint2)
	(visible waypoint2 waypoint1)
	(visible waypoint1 waypoint2)
	(visible waypoint2 waypoint3)
	(visible waypoint3 waypoint2)
	(visible waypoint2 waypoint4)
	(visible waypoint4 waypoint2)
	(visible waypoint3 waypoint4)
	(visible waypoint4 waypoint3)
	(visible waypoint3 waypoint5)
	(visible waypoint5 waypoint3)
	(visible waypoint4 waypoint0)
	(visible waypoint0 waypoint4)
	(visible waypoint4 waypoint1)
	(visible waypoint1 waypoint4)
	(visible waypoint5 waypoint2)
	(visible waypoint2 waypoint5)
	(visible waypoint5 waypoint4)
	(visible waypoint4 waypoint5)
	(= (recharges) 0)
	(in-sun waypoint0)
	(at-soil-sample waypoint1)
	(at-rock-sample waypoint2)
	(at-soil-sample waypoint3)
	(at-rock-sample waypoint3)
	(in-sun waypoint3)
	(at-soil-sample waypoint4)
	(at-rock-sample waypoint4)
	(in-sun waypoint4)
	(at-rock-sample waypoint5)
	(at-lander general waypoint0)
	(channel-free general)
	(= (energy rover0) 50)
	(in rover0 waypoint2)
	(available rover0)
	(store-of rover0store rover0)
	(empty rover0store)
	(equipped-for-soil-analysis rover0)
	(equipped-for-rock-analysis rover0)
	(can-traverse rover0 waypoint2 waypoint0)
	(can-traverse rover0 waypoint0 waypoint2)
	(can-traverse rover0 waypoint2 waypoint3)
	(can-traverse rover0 waypoint3 waypoint2)
	(can-traverse rover0 waypoint2 waypoint4)
	(can-traverse rover0 waypoint4 waypoint2)
	(can-traverse rover0 waypoint0 waypoint1)
	(can-traverse rover0 waypoint1 waypoint0)
	(can-traverse rover0 waypoint3 waypoint5)
	(can-traverse rover0 waypoint5 waypoint3)
	(= (energy rover1) 50)
	(in rover1 waypoint2)
	(available rover1)
	(store-of rover1store rover1)
	(empty rover1store)
	(equipped-for-rock-analysis rover1)
	(equipped-for-imaging rover1)
	(can-traverse rover1 waypoint2 waypoint0)
	(can-traverse rover1 waypoint0 waypoint2)
	(can-traverse rover1 waypoint2 waypoint3)
	(can-traverse rover1 waypoint3 waypoint2)
	(can-traverse rover1 waypoint2 waypoint5)
	(can-traverse rover1 waypoint5 waypoint2)
	(can-traverse rover1 waypoint0 waypoint1)
	(can-traverse rover1 waypoint1 waypoint0)
	(can-traverse rover1 waypoint3 waypoint4)
	(can-traverse rover1 waypoint4 waypoint3)
	(= (energy rover2) 50)
	(in rover2 waypoint2)
	(available rover2)
	(store-of rover2store rover2)
	(empty rover2store)
	(equipped-for-rock-analysis rover2)
	(equipped-for-imaging rover2)
	(can-traverse rover2 waypoint2 waypoint0)
	(can-traverse rover2 waypoint0 waypoint2)
	(can-traverse rover2 waypoint2 waypoint1)
	(can-traverse rover2 waypoint1 waypoint2)
	(can-traverse rover2 waypoint2 waypoint4)
	(can-traverse rover2 waypoint4 waypoint2)
	(can-traverse rover2 waypoint2 waypoint5)
	(can-traverse rover2 waypoint5 waypoint2)
	(can-traverse rover2 waypoint0 waypoint3)
	(can-traverse rover2 waypoint3 waypoint0)
	(= (energy rover3) 50)
	(in rover3 waypoint3)
	(available rover3)
	(store-of rover3store rover3)
	(empty rover3store)
	(equipped-for-soil-analysis rover3)
	(equipped-for-rock-analysis rover3)
	(equipped-for-imaging rover3)
	(can-traverse rover3 waypoint3 waypoint0)
	(can-traverse rover3 waypoint0 waypoint3)
	(can-traverse rover3 waypoint3 waypoint2)
	(can-traverse rover3 waypoint2 waypoint3)
	(can-traverse rover3 waypoint3 waypoint4)
	(can-traverse rover3 waypoint4 waypoint3)
	(can-traverse rover3 waypoint0 waypoint1)
	(can-traverse rover3 waypoint1 waypoint0)
	(can-traverse rover3 waypoint2 waypoint5)
	(can-traverse rover3 waypoint5 waypoint2)
	(on-board camera0 rover3)
	(calibration-target camera0 objective1)
	(supports camera0 colour)
	(supports camera0 high-res)
	(supports camera0 low-res)
	(on-board camera1 rover3)
	(calibration-target camera1 objective0)
	(supports camera1 colour)
	(supports camera1 high-res)
	(on-board camera2 rover1)
	(calibration-target camera2 objective0)
	(supports camera2 colour)
	(supports camera2 high-res)
	(supports camera2 low-res)
	(on-board camera3 rover2)
	(calibration-target camera3 objective1)
	(supports camera3 colour)
	(supports camera3 low-res)
	(visible-from objective0 waypoint0)
	(visible-from objective0 waypoint1)
	(visible-from objective0 waypoint2)
	(visible-from objective1 waypoint0)
	(visible-from objective2 waypoint0)
	(visible-from objective2 waypoint1)
	(visible-from objective2 waypoint2)
)

(:goal (and
(communicated-soil-data waypoint1)
(communicated-soil-data waypoint3)
(communicated-soil-data waypoint4)
(communicated-rock-data waypoint5)
(communicated-rock-data waypoint4)
(communicated-image-data objective0 low-res)
(communicated-image-data objective0 high-res)
(communicated-image-data objective2 low-res)
	)
)

(:metric minimize (recharges))
)
