(define (problem roverprob5142) (:domain rover)
(:objects
	general - lander
	colour high-res low-res - mode
	rover0 rover1 rover2 rover3 - agent
	rover0store rover1store rover2store rover3store - store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 - waypoint
	camera0 camera1 camera2 camera3 - camera
	objective0 objective1 objective2 objective3 objective4 - objective
	)
(:init
	(visible waypoint0 waypoint10)
	(visible waypoint10 waypoint0)
	(visible waypoint0 waypoint11)
	(visible waypoint11 waypoint0)
	(visible waypoint1 waypoint0)
	(visible waypoint0 waypoint1)
	(visible waypoint1 waypoint3)
	(visible waypoint3 waypoint1)
	(visible waypoint1 waypoint10)
	(visible waypoint10 waypoint1)
	(visible waypoint2 waypoint4)
	(visible waypoint4 waypoint2)
	(visible waypoint2 waypoint5)
	(visible waypoint5 waypoint2)
	(visible waypoint2 waypoint9)
	(visible waypoint9 waypoint2)
	(visible waypoint2 waypoint10)
	(visible waypoint10 waypoint2)
	(visible waypoint3 waypoint2)
	(visible waypoint2 waypoint3)
	(visible waypoint3 waypoint4)
	(visible waypoint4 waypoint3)
	(visible waypoint3 waypoint5)
	(visible waypoint5 waypoint3)
	(visible waypoint3 waypoint8)
	(visible waypoint8 waypoint3)
	(visible waypoint3 waypoint9)
	(visible waypoint9 waypoint3)
	(visible waypoint3 waypoint10)
	(visible waypoint10 waypoint3)
	(visible waypoint4 waypoint5)
	(visible waypoint5 waypoint4)
	(visible waypoint4 waypoint7)
	(visible waypoint7 waypoint4)
	(visible waypoint4 waypoint11)
	(visible waypoint11 waypoint4)
	(visible waypoint6 waypoint1)
	(visible waypoint1 waypoint6)
	(visible waypoint6 waypoint2)
	(visible waypoint2 waypoint6)
	(visible waypoint6 waypoint8)
	(visible waypoint8 waypoint6)
	(visible waypoint7 waypoint0)
	(visible waypoint0 waypoint7)
	(visible waypoint7 waypoint5)
	(visible waypoint5 waypoint7)
	(visible waypoint7 waypoint6)
	(visible waypoint6 waypoint7)
	(visible waypoint7 waypoint10)
	(visible waypoint10 waypoint7)
	(visible waypoint8 waypoint0)
	(visible waypoint0 waypoint8)
	(visible waypoint8 waypoint5)
	(visible waypoint5 waypoint8)
	(visible waypoint8 waypoint7)
	(visible waypoint7 waypoint8)
	(visible waypoint8 waypoint10)
	(visible waypoint10 waypoint8)
	(visible waypoint9 waypoint0)
	(visible waypoint0 waypoint9)
	(visible waypoint9 waypoint1)
	(visible waypoint1 waypoint9)
	(visible waypoint9 waypoint4)
	(visible waypoint4 waypoint9)
	(visible waypoint10 waypoint5)
	(visible waypoint5 waypoint10)
	(visible waypoint10 waypoint9)
	(visible waypoint9 waypoint10)
	(visible waypoint11 waypoint7)
	(visible waypoint7 waypoint11)
	(visible waypoint11 waypoint8)
	(visible waypoint8 waypoint11)
	(visible waypoint11 waypoint9)
	(visible waypoint9 waypoint11)
	(visible waypoint11 waypoint10)
	(visible waypoint10 waypoint11)
	(= (recharges) 0)
	(at-soil-sample waypoint0)
	(at-soil-sample waypoint1)
	(at-rock-sample waypoint1)
	(at-rock-sample waypoint2)
	(in-sun waypoint2)
	(at-rock-sample waypoint3)
	(at-soil-sample waypoint4)
	(at-soil-sample waypoint5)
	(at-rock-sample waypoint5)
	(at-soil-sample waypoint7)
	(at-soil-sample waypoint8)
	(at-rock-sample waypoint8)
	(at-soil-sample waypoint9)
	(at-rock-sample waypoint9)
	(at-rock-sample waypoint10)
	(in-sun waypoint10)
	(at-soil-sample waypoint11)
	(at-rock-sample waypoint11)
	(in-sun waypoint11)
	(at-lander general waypoint6)
	(channel-free general)
	(= (energy rover0) 50)
	(in rover0 waypoint6)
	(available rover0)
	(store-of rover0store rover0)
	(empty rover0store)
	(equipped-for-soil-analysis rover0)
	(equipped-for-rock-analysis rover0)
	(equipped-for-imaging rover0)
	(can-traverse rover0 waypoint6 waypoint1)
	(can-traverse rover0 waypoint1 waypoint6)
	(can-traverse rover0 waypoint6 waypoint2)
	(can-traverse rover0 waypoint2 waypoint6)
	(can-traverse rover0 waypoint6 waypoint7)
	(can-traverse rover0 waypoint7 waypoint6)
	(can-traverse rover0 waypoint1 waypoint0)
	(can-traverse rover0 waypoint0 waypoint1)
	(can-traverse rover0 waypoint1 waypoint3)
	(can-traverse rover0 waypoint3 waypoint1)
	(can-traverse rover0 waypoint1 waypoint9)
	(can-traverse rover0 waypoint9 waypoint1)
	(can-traverse rover0 waypoint2 waypoint5)
	(can-traverse rover0 waypoint5 waypoint2)
	(can-traverse rover0 waypoint7 waypoint4)
	(can-traverse rover0 waypoint4 waypoint7)
	(can-traverse rover0 waypoint7 waypoint8)
	(can-traverse rover0 waypoint8 waypoint7)
	(can-traverse rover0 waypoint7 waypoint10)
	(can-traverse rover0 waypoint10 waypoint7)
	(can-traverse rover0 waypoint7 waypoint11)
	(can-traverse rover0 waypoint11 waypoint7)
	(= (energy rover1) 50)
	(in rover1 waypoint2)
	(available rover1)
	(store-of rover1store rover1)
	(empty rover1store)
	(equipped-for-soil-analysis rover1)
	(equipped-for-rock-analysis rover1)
	(can-traverse rover1 waypoint2 waypoint3)
	(can-traverse rover1 waypoint3 waypoint2)
	(can-traverse rover1 waypoint2 waypoint4)
	(can-traverse rover1 waypoint4 waypoint2)
	(can-traverse rover1 waypoint2 waypoint5)
	(can-traverse rover1 waypoint5 waypoint2)
	(can-traverse rover1 waypoint2 waypoint6)
	(can-traverse rover1 waypoint6 waypoint2)
	(can-traverse rover1 waypoint2 waypoint9)
	(can-traverse rover1 waypoint9 waypoint2)
	(can-traverse rover1 waypoint2 waypoint10)
	(can-traverse rover1 waypoint10 waypoint2)
	(can-traverse rover1 waypoint3 waypoint1)
	(can-traverse rover1 waypoint1 waypoint3)
	(can-traverse rover1 waypoint3 waypoint8)
	(can-traverse rover1 waypoint8 waypoint3)
	(can-traverse rover1 waypoint4 waypoint7)
	(can-traverse rover1 waypoint7 waypoint4)
	(can-traverse rover1 waypoint9 waypoint11)
	(can-traverse rover1 waypoint11 waypoint9)
	(can-traverse rover1 waypoint1 waypoint0)
	(can-traverse rover1 waypoint0 waypoint1)
	(= (energy rover2) 50)
	(in rover2 waypoint9)
	(available rover2)
	(store-of rover2store rover2)
	(empty rover2store)
	(equipped-for-rock-analysis rover2)
	(equipped-for-imaging rover2)
	(can-traverse rover2 waypoint9 waypoint0)
	(can-traverse rover2 waypoint0 waypoint9)
	(can-traverse rover2 waypoint9 waypoint1)
	(can-traverse rover2 waypoint1 waypoint9)
	(can-traverse rover2 waypoint9 waypoint2)
	(can-traverse rover2 waypoint2 waypoint9)
	(can-traverse rover2 waypoint9 waypoint3)
	(can-traverse rover2 waypoint3 waypoint9)
	(can-traverse rover2 waypoint9 waypoint4)
	(can-traverse rover2 waypoint4 waypoint9)
	(can-traverse rover2 waypoint0 waypoint7)
	(can-traverse rover2 waypoint7 waypoint0)
	(can-traverse rover2 waypoint0 waypoint8)
	(can-traverse rover2 waypoint8 waypoint0)
	(can-traverse rover2 waypoint0 waypoint10)
	(can-traverse rover2 waypoint10 waypoint0)
	(can-traverse rover2 waypoint0 waypoint11)
	(can-traverse rover2 waypoint11 waypoint0)
	(can-traverse rover2 waypoint2 waypoint5)
	(can-traverse rover2 waypoint5 waypoint2)
	(can-traverse rover2 waypoint2 waypoint6)
	(can-traverse rover2 waypoint6 waypoint2)
	(= (energy rover3) 50)
	(in rover3 waypoint0)
	(available rover3)
	(store-of rover3store rover3)
	(empty rover3store)
	(equipped-for-rock-analysis rover3)
	(can-traverse rover3 waypoint0 waypoint1)
	(can-traverse rover3 waypoint1 waypoint0)
	(can-traverse rover3 waypoint0 waypoint8)
	(can-traverse rover3 waypoint8 waypoint0)
	(can-traverse rover3 waypoint0 waypoint9)
	(can-traverse rover3 waypoint9 waypoint0)
	(can-traverse rover3 waypoint0 waypoint10)
	(can-traverse rover3 waypoint10 waypoint0)
	(can-traverse rover3 waypoint0 waypoint11)
	(can-traverse rover3 waypoint11 waypoint0)
	(can-traverse rover3 waypoint1 waypoint3)
	(can-traverse rover3 waypoint3 waypoint1)
	(can-traverse rover3 waypoint1 waypoint6)
	(can-traverse rover3 waypoint6 waypoint1)
	(can-traverse rover3 waypoint9 waypoint4)
	(can-traverse rover3 waypoint4 waypoint9)
	(can-traverse rover3 waypoint10 waypoint2)
	(can-traverse rover3 waypoint2 waypoint10)
	(can-traverse rover3 waypoint10 waypoint5)
	(can-traverse rover3 waypoint5 waypoint10)
	(can-traverse rover3 waypoint10 waypoint7)
	(can-traverse rover3 waypoint7 waypoint10)
	(on-board camera0 rover2)
	(calibration-target camera0 objective3)
	(supports camera0 low-res)
	(on-board camera1 rover2)
	(calibration-target camera1 objective4)
	(supports camera1 colour)
	(on-board camera2 rover0)
	(calibration-target camera2 objective2)
	(supports camera2 high-res)
	(on-board camera3 rover2)
	(calibration-target camera3 objective3)
	(supports camera3 colour)
	(supports camera3 high-res)
	(supports camera3 low-res)
	(visible-from objective0 waypoint0)
	(visible-from objective0 waypoint1)
	(visible-from objective0 waypoint2)
	(visible-from objective0 waypoint3)
	(visible-from objective0 waypoint4)
	(visible-from objective0 waypoint5)
	(visible-from objective0 waypoint6)
	(visible-from objective0 waypoint7)
	(visible-from objective0 waypoint8)
	(visible-from objective1 waypoint0)
	(visible-from objective1 waypoint1)
	(visible-from objective1 waypoint2)
	(visible-from objective1 waypoint3)
	(visible-from objective1 waypoint4)
	(visible-from objective1 waypoint5)
	(visible-from objective1 waypoint6)
	(visible-from objective2 waypoint0)
	(visible-from objective2 waypoint1)
	(visible-from objective2 waypoint2)
	(visible-from objective2 waypoint3)
	(visible-from objective2 waypoint4)
	(visible-from objective2 waypoint5)
	(visible-from objective2 waypoint6)
	(visible-from objective2 waypoint7)
	(visible-from objective2 waypoint8)
	(visible-from objective2 waypoint9)
	(visible-from objective3 waypoint0)
	(visible-from objective3 waypoint1)
	(visible-from objective4 waypoint0)
	(visible-from objective4 waypoint1)
	(visible-from objective4 waypoint2)
	(visible-from objective4 waypoint3)
	(visible-from objective4 waypoint4)
	(visible-from objective4 waypoint5)
	(visible-from objective4 waypoint6)
	(visible-from objective4 waypoint7)
	(visible-from objective4 waypoint8)
	(visible-from objective4 waypoint9)
	(visible-from objective4 waypoint10)
)

(:goal (and
(communicated-soil-data waypoint4)
(communicated-soil-data waypoint9)
(communicated-soil-data waypoint1)
(communicated-soil-data waypoint7)
(communicated-rock-data waypoint3)
(communicated-rock-data waypoint10)
(communicated-rock-data waypoint5)
(communicated-rock-data waypoint1)
(communicated-image-data objective0 high-res)
(communicated-image-data objective4 high-res)
(communicated-image-data objective2 high-res)
	)
)

(:metric minimize (recharges))
)
