(define (problem num-gripper-x-9)
   (:domain multi-gripper-num)
   (:objects rooma roomb roomc roomd roome - room 
             ball20 ball19
             ball18 ball17 ball16 ball15 ball14 ball13 ball12 ball11 ball10
             ball9 ball8 ball7 ball6 ball5 ball4 ball3 ball2 ball1 - ball 
             r1 r2 - robby
             left1 right1 left2 right2 - gripper)
             
   (:init (= (weight ball20) 2)
          (= (weight ball19) 2)
          (= (weight ball18) 2)
          (= (weight ball17) 2)
          (= (weight ball16) 1)
          (= (weight ball15) 1)
          (= (weight ball14) 1)
          (= (weight ball13) 1)
          (= (weight ball12) 1)
          (= (weight ball11) 1)
          (= (weight ball10) 1)
          (= (weight ball9) 1)
          (= (weight ball8) 1)
          (= (weight ball7) 1)
          (= (weight ball6) 1)
          (= (weight ball5) 1)
          (= (weight ball4) 1)
          (= (weight ball3) 1)
          (= (weight ball2) 1)
          (= (weight ball1) 1)

          (at ball20 rooma)
          (at ball19 rooma)
          (at ball18 rooma)
          (at ball17 rooma)
          (at ball16 rooma)
          (at ball15 rooma)
          (at ball14 rooma)
          (at ball13 rooma)
          (at ball12 rooma)
          (at ball11 rooma)
          (at ball10 rooma)
          (at ball9 rooma)
          (at ball8 rooma)
          (at ball7 rooma)
          (at ball6 rooma)
          (at ball5 rooma)
          (at ball4 rooma)
          (at ball3 rooma)
          (at ball2 rooma)
          (at ball1 rooma)
          
          (at-robby r1 rooma)
          (at-robby r2 rooma)
          (free left1)
          (free right1)
          (free left2)
          (free right2)
          (mount left1 r1)
          (mount right1 r1)
          (mount left2 r2)
          (mount right2 r2)
          
          (door rooma roomb)
          (door roomb rooma)
          (door rooma roomc)
          (door roomc rooma)
          (door roomd roomb)
          (door roomb roomd)
          (door roomd roomc)
          (door roomc roomd)
          (door roomd roome)
          (door roome roomd)
          
          (= (current_load r1) 0)
          (= (load_limit r1) 8)
          (= (current_load r2) 0)
          (= (load_limit r2) 8)
          (= (cost) 0)
          )
   (:goal (and (at ball20 roome)
               (at ball19 roome)
               (at ball18 roome)
               (at ball17 roome)
               (at ball16 roome)
               (at ball15 roome)
               (at ball14 roome)
               (at ball13 roome)
               (at ball12 roome)
               (at ball11 roome)
               (at ball10 roome)
               (at ball9 roome)
               (at ball8 roome)
               (at ball7 roome)
               (at ball6 roome)
               (at ball5 roome)
               (at ball4 roome)
               (at ball3 roome)
               (at ball2 roome)
               (at ball1 roome)))
               
               (:metric minimize (cost))
               
)
