(define (problem roverprob7182) (:domain rover)
(:objects
	general - lander
	colour high-res low-res - mode
	rover0 rover1 rover2 rover3 rover4 rover5 rover6 rover7 - rover
	rover0store rover1store rover2store rover3store rover4store rover5store rover6store rover7store - store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 - waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 - camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - objective
	)
(:init
	(visible waypoint0 waypoint5)
	(visible waypoint5 waypoint0)
	(visible waypoint0 waypoint15)
	(visible waypoint15 waypoint0)
	(visible waypoint0 waypoint23)
	(visible waypoint23 waypoint0)
	(visible waypoint1 waypoint23)
	(visible waypoint23 waypoint1)
	(visible waypoint2 waypoint1)
	(visible waypoint1 waypoint2)
	(visible waypoint2 waypoint5)
	(visible waypoint5 waypoint2)
	(visible waypoint2 waypoint6)
	(visible waypoint6 waypoint2)
	(visible waypoint2 waypoint14)
	(visible waypoint14 waypoint2)
	(visible waypoint2 waypoint16)
	(visible waypoint16 waypoint2)
	(visible waypoint2 waypoint23)
	(visible waypoint23 waypoint2)
	(visible waypoint3 waypoint1)
	(visible waypoint1 waypoint3)
	(visible waypoint3 waypoint13)
	(visible waypoint13 waypoint3)
	(visible waypoint3 waypoint15)
	(visible waypoint15 waypoint3)
	(visible waypoint3 waypoint18)
	(visible waypoint18 waypoint3)
	(visible waypoint3 waypoint20)
	(visible waypoint20 waypoint3)
	(visible waypoint4 waypoint1)
	(visible waypoint1 waypoint4)
	(visible waypoint4 waypoint6)
	(visible waypoint6 waypoint4)
	(visible waypoint4 waypoint13)
	(visible waypoint13 waypoint4)
	(visible waypoint4 waypoint16)
	(visible waypoint16 waypoint4)
	(visible waypoint4 waypoint19)
	(visible waypoint19 waypoint4)
	(visible waypoint4 waypoint20)
	(visible waypoint20 waypoint4)
	(visible waypoint5 waypoint1)
	(visible waypoint1 waypoint5)
	(visible waypoint5 waypoint4)
	(visible waypoint4 waypoint5)
	(visible waypoint5 waypoint8)
	(visible waypoint8 waypoint5)
	(visible waypoint5 waypoint16)
	(visible waypoint16 waypoint5)
	(visible waypoint6 waypoint5)
	(visible waypoint5 waypoint6)
	(visible waypoint6 waypoint8)
	(visible waypoint8 waypoint6)
	(visible waypoint6 waypoint9)
	(visible waypoint9 waypoint6)
	(visible waypoint6 waypoint11)
	(visible waypoint11 waypoint6)
	(visible waypoint6 waypoint21)
	(visible waypoint21 waypoint6)
	(visible waypoint7 waypoint0)
	(visible waypoint0 waypoint7)
	(visible waypoint7 waypoint4)
	(visible waypoint4 waypoint7)
	(visible waypoint7 waypoint8)
	(visible waypoint8 waypoint7)
	(visible waypoint7 waypoint16)
	(visible waypoint16 waypoint7)
	(visible waypoint7 waypoint17)
	(visible waypoint17 waypoint7)
	(visible waypoint8 waypoint4)
	(visible waypoint4 waypoint8)
	(visible waypoint8 waypoint16)
	(visible waypoint16 waypoint8)
	(visible waypoint8 waypoint17)
	(visible waypoint17 waypoint8)
	(visible waypoint9 waypoint2)
	(visible waypoint2 waypoint9)
	(visible waypoint9 waypoint5)
	(visible waypoint5 waypoint9)
	(visible waypoint9 waypoint7)
	(visible waypoint7 waypoint9)
	(visible waypoint9 waypoint14)
	(visible waypoint14 waypoint9)
	(visible waypoint9 waypoint17)
	(visible waypoint17 waypoint9)
	(visible waypoint10 waypoint11)
	(visible waypoint11 waypoint10)
	(visible waypoint10 waypoint15)
	(visible waypoint15 waypoint10)
	(visible waypoint11 waypoint8)
	(visible waypoint8 waypoint11)
	(visible waypoint11 waypoint19)
	(visible waypoint19 waypoint11)
	(visible waypoint12 waypoint3)
	(visible waypoint3 waypoint12)
	(visible waypoint12 waypoint6)
	(visible waypoint6 waypoint12)
	(visible waypoint12 waypoint11)
	(visible waypoint11 waypoint12)
	(visible waypoint12 waypoint13)
	(visible waypoint13 waypoint12)
	(visible waypoint12 waypoint19)
	(visible waypoint19 waypoint12)
	(visible waypoint12 waypoint22)
	(visible waypoint22 waypoint12)
	(visible waypoint12 waypoint23)
	(visible waypoint23 waypoint12)
	(visible waypoint12 waypoint24)
	(visible waypoint24 waypoint12)
	(visible waypoint13 waypoint14)
	(visible waypoint14 waypoint13)
	(visible waypoint13 waypoint15)
	(visible waypoint15 waypoint13)
	(visible waypoint13 waypoint20)
	(visible waypoint20 waypoint13)
	(visible waypoint14 waypoint0)
	(visible waypoint0 waypoint14)
	(visible waypoint14 waypoint1)
	(visible waypoint1 waypoint14)
	(visible waypoint14 waypoint5)
	(visible waypoint5 waypoint14)
	(visible waypoint14 waypoint6)
	(visible waypoint6 waypoint14)
	(visible waypoint14 waypoint8)
	(visible waypoint8 waypoint14)
	(visible waypoint14 waypoint12)
	(visible waypoint12 waypoint14)
	(visible waypoint14 waypoint20)
	(visible waypoint20 waypoint14)
	(visible waypoint15 waypoint1)
	(visible waypoint1 waypoint15)
	(visible waypoint15 waypoint6)
	(visible waypoint6 waypoint15)
	(visible waypoint15 waypoint12)
	(visible waypoint12 waypoint15)
	(visible waypoint15 waypoint16)
	(visible waypoint16 waypoint15)
	(visible waypoint16 waypoint10)
	(visible waypoint10 waypoint16)
	(visible waypoint16 waypoint20)
	(visible waypoint20 waypoint16)
	(visible waypoint17 waypoint11)
	(visible waypoint11 waypoint17)
	(visible waypoint17 waypoint14)
	(visible waypoint14 waypoint17)
	(visible waypoint17 waypoint15)
	(visible waypoint15 waypoint17)
	(visible waypoint17 waypoint18)
	(visible waypoint18 waypoint17)
	(visible waypoint17 waypoint20)
	(visible waypoint20 waypoint17)
	(visible waypoint18 waypoint0)
	(visible waypoint0 waypoint18)
	(visible waypoint18 waypoint1)
	(visible waypoint1 waypoint18)
	(visible waypoint18 waypoint6)
	(visible waypoint6 waypoint18)
	(visible waypoint18 waypoint8)
	(visible waypoint8 waypoint18)
	(visible waypoint18 waypoint9)
	(visible waypoint9 waypoint18)
	(visible waypoint18 waypoint10)
	(visible waypoint10 waypoint18)
	(visible waypoint19 waypoint6)
	(visible waypoint6 waypoint19)
	(visible waypoint19 waypoint21)
	(visible waypoint21 waypoint19)
	(visible waypoint20 waypoint19)
	(visible waypoint19 waypoint20)
	(visible waypoint21 waypoint4)
	(visible waypoint4 waypoint21)
	(visible waypoint21 waypoint5)
	(visible waypoint5 waypoint21)
	(visible waypoint21 waypoint8)
	(visible waypoint8 waypoint21)
	(visible waypoint21 waypoint11)
	(visible waypoint11 waypoint21)
	(visible waypoint21 waypoint13)
	(visible waypoint13 waypoint21)
	(visible waypoint21 waypoint17)
	(visible waypoint17 waypoint21)
	(visible waypoint21 waypoint18)
	(visible waypoint18 waypoint21)
	(visible waypoint22 waypoint11)
	(visible waypoint11 waypoint22)
	(visible waypoint22 waypoint16)
	(visible waypoint16 waypoint22)
	(visible waypoint22 waypoint21)
	(visible waypoint21 waypoint22)
	(visible waypoint23 waypoint10)
	(visible waypoint10 waypoint23)
	(visible waypoint23 waypoint18)
	(visible waypoint18 waypoint23)
	(visible waypoint23 waypoint20)
	(visible waypoint20 waypoint23)
	(visible waypoint24 waypoint5)
	(visible waypoint5 waypoint24)
	(visible waypoint24 waypoint7)
	(visible waypoint7 waypoint24)
	(visible waypoint24 waypoint18)
	(visible waypoint18 waypoint24)
	(visible waypoint24 waypoint20)
	(visible waypoint20 waypoint24)
	(visible waypoint24 waypoint23)
	(visible waypoint23 waypoint24)
	(= (recharges) 0)
	(at-soil-sample waypoint0)
	(in-sun waypoint0)
	(at-soil-sample waypoint1)
	(at-soil-sample waypoint7)
	(at-rock-sample waypoint7)
	(at-soil-sample waypoint8)
	(at-soil-sample waypoint9)
	(at-rock-sample waypoint9)
	(at-rock-sample waypoint10)
	(in-sun waypoint10)
	(at-soil-sample waypoint11)
	(at-rock-sample waypoint12)
	(in-sun waypoint12)
	(at-soil-sample waypoint13)
	(at-rock-sample waypoint14)
	(in-sun waypoint14)
	(at-soil-sample waypoint15)
	(at-rock-sample waypoint16)
	(in-sun waypoint16)
	(at-soil-sample waypoint17)
	(at-soil-sample waypoint18)
	(at-rock-sample waypoint18)
	(in-sun waypoint19)
	(at-soil-sample waypoint20)
	(at-rock-sample waypoint21)
	(at-soil-sample waypoint22)
	(at-rock-sample waypoint22)
	(at-soil-sample waypoint23)
	(in-sun waypoint23)
	(at-soil-sample waypoint24)
	(in-sun waypoint24)
	(at-lander general waypoint1)
	(channel-free general)
	(= (energy rover0) 50)
	(in rover0 waypoint22)
	(available rover0)
	(store-of rover0store rover0)
	(empty rover0store)
	(equipped-for-soil-analysis rover0)
	(equipped-for-imaging rover0)
	(can-traverse rover0 waypoint22 waypoint11)
	(can-traverse rover0 waypoint11 waypoint22)
	(can-traverse rover0 waypoint22 waypoint12)
	(can-traverse rover0 waypoint12 waypoint22)
	(can-traverse rover0 waypoint22 waypoint21)
	(can-traverse rover0 waypoint21 waypoint22)
	(can-traverse rover0 waypoint11 waypoint6)
	(can-traverse rover0 waypoint6 waypoint11)
	(can-traverse rover0 waypoint11 waypoint8)
	(can-traverse rover0 waypoint8 waypoint11)
	(can-traverse rover0 waypoint11 waypoint10)
	(can-traverse rover0 waypoint10 waypoint11)
	(can-traverse rover0 waypoint11 waypoint17)
	(can-traverse rover0 waypoint17 waypoint11)
	(can-traverse rover0 waypoint11 waypoint19)
	(can-traverse rover0 waypoint19 waypoint11)
	(can-traverse rover0 waypoint12 waypoint13)
	(can-traverse rover0 waypoint13 waypoint12)
	(can-traverse rover0 waypoint12 waypoint15)
	(can-traverse rover0 waypoint15 waypoint12)
	(can-traverse rover0 waypoint12 waypoint24)
	(can-traverse rover0 waypoint24 waypoint12)
	(can-traverse rover0 waypoint21 waypoint4)
	(can-traverse rover0 waypoint4 waypoint21)
	(can-traverse rover0 waypoint21 waypoint5)
	(can-traverse rover0 waypoint5 waypoint21)
	(can-traverse rover0 waypoint21 waypoint18)
	(can-traverse rover0 waypoint18 waypoint21)
	(can-traverse rover0 waypoint6 waypoint2)
	(can-traverse rover0 waypoint2 waypoint6)
	(can-traverse rover0 waypoint6 waypoint9)
	(can-traverse rover0 waypoint9 waypoint6)
	(can-traverse rover0 waypoint6 waypoint14)
	(can-traverse rover0 waypoint14 waypoint6)
	(can-traverse rover0 waypoint8 waypoint7)
	(can-traverse rover0 waypoint7 waypoint8)
	(can-traverse rover0 waypoint17 waypoint20)
	(can-traverse rover0 waypoint20 waypoint17)
	(can-traverse rover0 waypoint13 waypoint3)
	(can-traverse rover0 waypoint3 waypoint13)
	(can-traverse rover0 waypoint15 waypoint1)
	(can-traverse rover0 waypoint1 waypoint15)
	(can-traverse rover0 waypoint15 waypoint16)
	(can-traverse rover0 waypoint16 waypoint15)
	(can-traverse rover0 waypoint24 waypoint23)
	(can-traverse rover0 waypoint23 waypoint24)
	(can-traverse rover0 waypoint5 waypoint0)
	(can-traverse rover0 waypoint0 waypoint5)
	(= (energy rover1) 50)
	(in rover1 waypoint4)
	(available rover1)
	(store-of rover1store rover1)
	(empty rover1store)
	(equipped-for-imaging rover1)
	(can-traverse rover1 waypoint4 waypoint1)
	(can-traverse rover1 waypoint1 waypoint4)
	(can-traverse rover1 waypoint4 waypoint5)
	(can-traverse rover1 waypoint5 waypoint4)
	(can-traverse rover1 waypoint4 waypoint6)
	(can-traverse rover1 waypoint6 waypoint4)
	(can-traverse rover1 waypoint4 waypoint13)
	(can-traverse rover1 waypoint13 waypoint4)
	(can-traverse rover1 waypoint4 waypoint16)
	(can-traverse rover1 waypoint16 waypoint4)
	(can-traverse rover1 waypoint4 waypoint19)
	(can-traverse rover1 waypoint19 waypoint4)
	(can-traverse rover1 waypoint4 waypoint20)
	(can-traverse rover1 waypoint20 waypoint4)
	(can-traverse rover1 waypoint4 waypoint21)
	(can-traverse rover1 waypoint21 waypoint4)
	(can-traverse rover1 waypoint1 waypoint14)
	(can-traverse rover1 waypoint14 waypoint1)
	(can-traverse rover1 waypoint1 waypoint15)
	(can-traverse rover1 waypoint15 waypoint1)
	(can-traverse rover1 waypoint1 waypoint18)
	(can-traverse rover1 waypoint18 waypoint1)
	(can-traverse rover1 waypoint5 waypoint0)
	(can-traverse rover1 waypoint0 waypoint5)
	(can-traverse rover1 waypoint5 waypoint2)
	(can-traverse rover1 waypoint2 waypoint5)
	(can-traverse rover1 waypoint5 waypoint8)
	(can-traverse rover1 waypoint8 waypoint5)
	(can-traverse rover1 waypoint5 waypoint9)
	(can-traverse rover1 waypoint9 waypoint5)
	(can-traverse rover1 waypoint5 waypoint24)
	(can-traverse rover1 waypoint24 waypoint5)
	(can-traverse rover1 waypoint6 waypoint11)
	(can-traverse rover1 waypoint11 waypoint6)
	(can-traverse rover1 waypoint6 waypoint12)
	(can-traverse rover1 waypoint12 waypoint6)
	(can-traverse rover1 waypoint13 waypoint3)
	(can-traverse rover1 waypoint3 waypoint13)
	(can-traverse rover1 waypoint16 waypoint22)
	(can-traverse rover1 waypoint22 waypoint16)
	(can-traverse rover1 waypoint20 waypoint17)
	(can-traverse rover1 waypoint17 waypoint20)
	(can-traverse rover1 waypoint18 waypoint10)
	(can-traverse rover1 waypoint10 waypoint18)
	(can-traverse rover1 waypoint18 waypoint23)
	(can-traverse rover1 waypoint23 waypoint18)
	(can-traverse rover1 waypoint0 waypoint7)
	(can-traverse rover1 waypoint7 waypoint0)
	(= (energy rover2) 50)
	(in rover2 waypoint3)
	(available rover2)
	(store-of rover2store rover2)
	(empty rover2store)
	(equipped-for-rock-analysis rover2)
	(equipped-for-imaging rover2)
	(can-traverse rover2 waypoint3 waypoint1)
	(can-traverse rover2 waypoint1 waypoint3)
	(can-traverse rover2 waypoint3 waypoint13)
	(can-traverse rover2 waypoint13 waypoint3)
	(can-traverse rover2 waypoint3 waypoint18)
	(can-traverse rover2 waypoint18 waypoint3)
	(can-traverse rover2 waypoint3 waypoint20)
	(can-traverse rover2 waypoint20 waypoint3)
	(can-traverse rover2 waypoint1 waypoint2)
	(can-traverse rover2 waypoint2 waypoint1)
	(can-traverse rover2 waypoint1 waypoint5)
	(can-traverse rover2 waypoint5 waypoint1)
	(can-traverse rover2 waypoint1 waypoint14)
	(can-traverse rover2 waypoint14 waypoint1)
	(can-traverse rover2 waypoint1 waypoint15)
	(can-traverse rover2 waypoint15 waypoint1)
	(can-traverse rover2 waypoint13 waypoint4)
	(can-traverse rover2 waypoint4 waypoint13)
	(can-traverse rover2 waypoint13 waypoint21)
	(can-traverse rover2 waypoint21 waypoint13)
	(can-traverse rover2 waypoint18 waypoint6)
	(can-traverse rover2 waypoint6 waypoint18)
	(can-traverse rover2 waypoint18 waypoint9)
	(can-traverse rover2 waypoint9 waypoint18)
	(can-traverse rover2 waypoint18 waypoint17)
	(can-traverse rover2 waypoint17 waypoint18)
	(can-traverse rover2 waypoint18 waypoint23)
	(can-traverse rover2 waypoint23 waypoint18)
	(can-traverse rover2 waypoint18 waypoint24)
	(can-traverse rover2 waypoint24 waypoint18)
	(can-traverse rover2 waypoint20 waypoint16)
	(can-traverse rover2 waypoint16 waypoint20)
	(can-traverse rover2 waypoint20 waypoint19)
	(can-traverse rover2 waypoint19 waypoint20)
	(can-traverse rover2 waypoint5 waypoint0)
	(can-traverse rover2 waypoint0 waypoint5)
	(can-traverse rover2 waypoint5 waypoint8)
	(can-traverse rover2 waypoint8 waypoint5)
	(can-traverse rover2 waypoint14 waypoint12)
	(can-traverse rover2 waypoint12 waypoint14)
	(can-traverse rover2 waypoint15 waypoint10)
	(can-traverse rover2 waypoint10 waypoint15)
	(can-traverse rover2 waypoint4 waypoint7)
	(can-traverse rover2 waypoint7 waypoint4)
	(can-traverse rover2 waypoint21 waypoint11)
	(can-traverse rover2 waypoint11 waypoint21)
	(can-traverse rover2 waypoint21 waypoint22)
	(can-traverse rover2 waypoint22 waypoint21)
	(= (energy rover3) 50)
	(in rover3 waypoint3)
	(available rover3)
	(store-of rover3store rover3)
	(empty rover3store)
	(equipped-for-soil-analysis rover3)
	(equipped-for-rock-analysis rover3)
	(can-traverse rover3 waypoint3 waypoint1)
	(can-traverse rover3 waypoint1 waypoint3)
	(can-traverse rover3 waypoint3 waypoint12)
	(can-traverse rover3 waypoint12 waypoint3)
	(can-traverse rover3 waypoint3 waypoint13)
	(can-traverse rover3 waypoint13 waypoint3)
	(can-traverse rover3 waypoint3 waypoint18)
	(can-traverse rover3 waypoint18 waypoint3)
	(can-traverse rover3 waypoint3 waypoint20)
	(can-traverse rover3 waypoint20 waypoint3)
	(can-traverse rover3 waypoint1 waypoint2)
	(can-traverse rover3 waypoint2 waypoint1)
	(can-traverse rover3 waypoint1 waypoint4)
	(can-traverse rover3 waypoint4 waypoint1)
	(can-traverse rover3 waypoint1 waypoint5)
	(can-traverse rover3 waypoint5 waypoint1)
	(can-traverse rover3 waypoint1 waypoint14)
	(can-traverse rover3 waypoint14 waypoint1)
	(can-traverse rover3 waypoint1 waypoint15)
	(can-traverse rover3 waypoint15 waypoint1)
	(can-traverse rover3 waypoint1 waypoint23)
	(can-traverse rover3 waypoint23 waypoint1)
	(can-traverse rover3 waypoint12 waypoint6)
	(can-traverse rover3 waypoint6 waypoint12)
	(can-traverse rover3 waypoint12 waypoint19)
	(can-traverse rover3 waypoint19 waypoint12)
	(can-traverse rover3 waypoint12 waypoint22)
	(can-traverse rover3 waypoint22 waypoint12)
	(can-traverse rover3 waypoint12 waypoint24)
	(can-traverse rover3 waypoint24 waypoint12)
	(can-traverse rover3 waypoint13 waypoint21)
	(can-traverse rover3 waypoint21 waypoint13)
	(can-traverse rover3 waypoint18 waypoint0)
	(can-traverse rover3 waypoint0 waypoint18)
	(can-traverse rover3 waypoint18 waypoint9)
	(can-traverse rover3 waypoint9 waypoint18)
	(can-traverse rover3 waypoint18 waypoint17)
	(can-traverse rover3 waypoint17 waypoint18)
	(can-traverse rover3 waypoint20 waypoint16)
	(can-traverse rover3 waypoint16 waypoint20)
	(can-traverse rover3 waypoint4 waypoint7)
	(can-traverse rover3 waypoint7 waypoint4)
	(can-traverse rover3 waypoint4 waypoint8)
	(can-traverse rover3 waypoint8 waypoint4)
	(can-traverse rover3 waypoint6 waypoint11)
	(can-traverse rover3 waypoint11 waypoint6)
	(can-traverse rover3 waypoint16 waypoint10)
	(can-traverse rover3 waypoint10 waypoint16)
	(= (energy rover4) 50)
	(in rover4 waypoint16)
	(available rover4)
	(store-of rover4store rover4)
	(empty rover4store)
	(equipped-for-rock-analysis rover4)
	(equipped-for-imaging rover4)
	(can-traverse rover4 waypoint16 waypoint2)
	(can-traverse rover4 waypoint2 waypoint16)
	(can-traverse rover4 waypoint16 waypoint4)
	(can-traverse rover4 waypoint4 waypoint16)
	(can-traverse rover4 waypoint16 waypoint5)
	(can-traverse rover4 waypoint5 waypoint16)
	(can-traverse rover4 waypoint16 waypoint7)
	(can-traverse rover4 waypoint7 waypoint16)
	(can-traverse rover4 waypoint16 waypoint8)
	(can-traverse rover4 waypoint8 waypoint16)
	(can-traverse rover4 waypoint16 waypoint10)
	(can-traverse rover4 waypoint10 waypoint16)
	(can-traverse rover4 waypoint16 waypoint15)
	(can-traverse rover4 waypoint15 waypoint16)
	(can-traverse rover4 waypoint16 waypoint22)
	(can-traverse rover4 waypoint22 waypoint16)
	(can-traverse rover4 waypoint2 waypoint9)
	(can-traverse rover4 waypoint9 waypoint2)
	(can-traverse rover4 waypoint2 waypoint14)
	(can-traverse rover4 waypoint14 waypoint2)
	(can-traverse rover4 waypoint4 waypoint1)
	(can-traverse rover4 waypoint1 waypoint4)
	(can-traverse rover4 waypoint4 waypoint13)
	(can-traverse rover4 waypoint13 waypoint4)
	(can-traverse rover4 waypoint4 waypoint20)
	(can-traverse rover4 waypoint20 waypoint4)
	(can-traverse rover4 waypoint5 waypoint0)
	(can-traverse rover4 waypoint0 waypoint5)
	(can-traverse rover4 waypoint5 waypoint21)
	(can-traverse rover4 waypoint21 waypoint5)
	(can-traverse rover4 waypoint5 waypoint24)
	(can-traverse rover4 waypoint24 waypoint5)
	(can-traverse rover4 waypoint7 waypoint17)
	(can-traverse rover4 waypoint17 waypoint7)
	(can-traverse rover4 waypoint8 waypoint11)
	(can-traverse rover4 waypoint11 waypoint8)
	(can-traverse rover4 waypoint8 waypoint18)
	(can-traverse rover4 waypoint18 waypoint8)
	(can-traverse rover4 waypoint15 waypoint3)
	(can-traverse rover4 waypoint3 waypoint15)
	(can-traverse rover4 waypoint15 waypoint6)
	(can-traverse rover4 waypoint6 waypoint15)
	(can-traverse rover4 waypoint15 waypoint12)
	(can-traverse rover4 waypoint12 waypoint15)
	(can-traverse rover4 waypoint20 waypoint23)
	(can-traverse rover4 waypoint23 waypoint20)
	(can-traverse rover4 waypoint21 waypoint19)
	(can-traverse rover4 waypoint19 waypoint21)
	(= (energy rover5) 50)
	(in rover5 waypoint10)
	(available rover5)
	(store-of rover5store rover5)
	(empty rover5store)
	(equipped-for-imaging rover5)
	(can-traverse rover5 waypoint10 waypoint11)
	(can-traverse rover5 waypoint11 waypoint10)
	(can-traverse rover5 waypoint10 waypoint15)
	(can-traverse rover5 waypoint15 waypoint10)
	(can-traverse rover5 waypoint10 waypoint16)
	(can-traverse rover5 waypoint16 waypoint10)
	(can-traverse rover5 waypoint10 waypoint18)
	(can-traverse rover5 waypoint18 waypoint10)
	(can-traverse rover5 waypoint10 waypoint23)
	(can-traverse rover5 waypoint23 waypoint10)
	(can-traverse rover5 waypoint11 waypoint6)
	(can-traverse rover5 waypoint6 waypoint11)
	(can-traverse rover5 waypoint11 waypoint8)
	(can-traverse rover5 waypoint8 waypoint11)
	(can-traverse rover5 waypoint11 waypoint12)
	(can-traverse rover5 waypoint12 waypoint11)
	(can-traverse rover5 waypoint11 waypoint21)
	(can-traverse rover5 waypoint21 waypoint11)
	(can-traverse rover5 waypoint11 waypoint22)
	(can-traverse rover5 waypoint22 waypoint11)
	(can-traverse rover5 waypoint15 waypoint0)
	(can-traverse rover5 waypoint0 waypoint15)
	(can-traverse rover5 waypoint15 waypoint1)
	(can-traverse rover5 waypoint1 waypoint15)
	(can-traverse rover5 waypoint15 waypoint13)
	(can-traverse rover5 waypoint13 waypoint15)
	(can-traverse rover5 waypoint15 waypoint17)
	(can-traverse rover5 waypoint17 waypoint15)
	(can-traverse rover5 waypoint16 waypoint2)
	(can-traverse rover5 waypoint2 waypoint16)
	(can-traverse rover5 waypoint16 waypoint4)
	(can-traverse rover5 waypoint4 waypoint16)
	(can-traverse rover5 waypoint16 waypoint7)
	(can-traverse rover5 waypoint7 waypoint16)
	(can-traverse rover5 waypoint18 waypoint3)
	(can-traverse rover5 waypoint3 waypoint18)
	(can-traverse rover5 waypoint23 waypoint20)
	(can-traverse rover5 waypoint20 waypoint23)
	(can-traverse rover5 waypoint23 waypoint24)
	(can-traverse rover5 waypoint24 waypoint23)
	(can-traverse rover5 waypoint6 waypoint5)
	(can-traverse rover5 waypoint5 waypoint6)
	(can-traverse rover5 waypoint6 waypoint9)
	(can-traverse rover5 waypoint9 waypoint6)
	(can-traverse rover5 waypoint6 waypoint14)
	(can-traverse rover5 waypoint14 waypoint6)
	(can-traverse rover5 waypoint6 waypoint19)
	(can-traverse rover5 waypoint19 waypoint6)
	(= (energy rover6) 50)
	(in rover6 waypoint4)
	(available rover6)
	(store-of rover6store rover6)
	(empty rover6store)
	(equipped-for-soil-analysis rover6)
	(equipped-for-imaging rover6)
	(can-traverse rover6 waypoint4 waypoint1)
	(can-traverse rover6 waypoint1 waypoint4)
	(can-traverse rover6 waypoint4 waypoint6)
	(can-traverse rover6 waypoint6 waypoint4)
	(can-traverse rover6 waypoint4 waypoint8)
	(can-traverse rover6 waypoint8 waypoint4)
	(can-traverse rover6 waypoint4 waypoint13)
	(can-traverse rover6 waypoint13 waypoint4)
	(can-traverse rover6 waypoint4 waypoint16)
	(can-traverse rover6 waypoint16 waypoint4)
	(can-traverse rover6 waypoint4 waypoint19)
	(can-traverse rover6 waypoint19 waypoint4)
	(can-traverse rover6 waypoint4 waypoint20)
	(can-traverse rover6 waypoint20 waypoint4)
	(can-traverse rover6 waypoint1 waypoint3)
	(can-traverse rover6 waypoint3 waypoint1)
	(can-traverse rover6 waypoint1 waypoint5)
	(can-traverse rover6 waypoint5 waypoint1)
	(can-traverse rover6 waypoint1 waypoint14)
	(can-traverse rover6 waypoint14 waypoint1)
	(can-traverse rover6 waypoint1 waypoint18)
	(can-traverse rover6 waypoint18 waypoint1)
	(can-traverse rover6 waypoint1 waypoint23)
	(can-traverse rover6 waypoint23 waypoint1)
	(can-traverse rover6 waypoint6 waypoint2)
	(can-traverse rover6 waypoint2 waypoint6)
	(can-traverse rover6 waypoint6 waypoint9)
	(can-traverse rover6 waypoint9 waypoint6)
	(can-traverse rover6 waypoint6 waypoint11)
	(can-traverse rover6 waypoint11 waypoint6)
	(can-traverse rover6 waypoint6 waypoint12)
	(can-traverse rover6 waypoint12 waypoint6)
	(can-traverse rover6 waypoint6 waypoint15)
	(can-traverse rover6 waypoint15 waypoint6)
	(can-traverse rover6 waypoint6 waypoint21)
	(can-traverse rover6 waypoint21 waypoint6)
	(can-traverse rover6 waypoint8 waypoint17)
	(can-traverse rover6 waypoint17 waypoint8)
	(can-traverse rover6 waypoint16 waypoint7)
	(can-traverse rover6 waypoint7 waypoint16)
	(can-traverse rover6 waypoint16 waypoint10)
	(can-traverse rover6 waypoint10 waypoint16)
	(can-traverse rover6 waypoint16 waypoint22)
	(can-traverse rover6 waypoint22 waypoint16)
	(can-traverse rover6 waypoint20 waypoint24)
	(can-traverse rover6 waypoint24 waypoint20)
	(can-traverse rover6 waypoint23 waypoint0)
	(can-traverse rover6 waypoint0 waypoint23)
	(= (energy rover7) 50)
	(in rover7 waypoint16)
	(available rover7)
	(store-of rover7store rover7)
	(empty rover7store)
	(equipped-for-rock-analysis rover7)
	(can-traverse rover7 waypoint16 waypoint2)
	(can-traverse rover7 waypoint2 waypoint16)
	(can-traverse rover7 waypoint16 waypoint4)
	(can-traverse rover7 waypoint4 waypoint16)
	(can-traverse rover7 waypoint16 waypoint8)
	(can-traverse rover7 waypoint8 waypoint16)
	(can-traverse rover7 waypoint16 waypoint10)
	(can-traverse rover7 waypoint10 waypoint16)
	(can-traverse rover7 waypoint16 waypoint20)
	(can-traverse rover7 waypoint20 waypoint16)
	(can-traverse rover7 waypoint2 waypoint5)
	(can-traverse rover7 waypoint5 waypoint2)
	(can-traverse rover7 waypoint2 waypoint6)
	(can-traverse rover7 waypoint6 waypoint2)
	(can-traverse rover7 waypoint2 waypoint9)
	(can-traverse rover7 waypoint9 waypoint2)
	(can-traverse rover7 waypoint2 waypoint14)
	(can-traverse rover7 waypoint14 waypoint2)
	(can-traverse rover7 waypoint2 waypoint23)
	(can-traverse rover7 waypoint23 waypoint2)
	(can-traverse rover7 waypoint4 waypoint13)
	(can-traverse rover7 waypoint13 waypoint4)
	(can-traverse rover7 waypoint4 waypoint19)
	(can-traverse rover7 waypoint19 waypoint4)
	(can-traverse rover7 waypoint8 waypoint7)
	(can-traverse rover7 waypoint7 waypoint8)
	(can-traverse rover7 waypoint8 waypoint17)
	(can-traverse rover7 waypoint17 waypoint8)
	(can-traverse rover7 waypoint8 waypoint18)
	(can-traverse rover7 waypoint18 waypoint8)
	(can-traverse rover7 waypoint10 waypoint11)
	(can-traverse rover7 waypoint11 waypoint10)
	(can-traverse rover7 waypoint10 waypoint15)
	(can-traverse rover7 waypoint15 waypoint10)
	(can-traverse rover7 waypoint20 waypoint3)
	(can-traverse rover7 waypoint3 waypoint20)
	(can-traverse rover7 waypoint20 waypoint24)
	(can-traverse rover7 waypoint24 waypoint20)
	(can-traverse rover7 waypoint5 waypoint21)
	(can-traverse rover7 waypoint21 waypoint5)
	(can-traverse rover7 waypoint6 waypoint12)
	(can-traverse rover7 waypoint12 waypoint6)
	(can-traverse rover7 waypoint14 waypoint0)
	(can-traverse rover7 waypoint0 waypoint14)
	(can-traverse rover7 waypoint14 waypoint1)
	(can-traverse rover7 waypoint1 waypoint14)
	(on-board camera0 rover0)
	(calibration-target camera0 objective6)
	(supports camera0 colour)
	(supports camera0 high-res)
	(on-board camera1 rover1)
	(calibration-target camera1 objective1)
	(supports camera1 colour)
	(supports camera1 high-res)
	(on-board camera2 rover4)
	(calibration-target camera2 objective0)
	(supports camera2 colour)
	(supports camera2 high-res)
	(supports camera2 low-res)
	(on-board camera3 rover2)
	(calibration-target camera3 objective2)
	(supports camera3 high-res)
	(supports camera3 low-res)
	(on-board camera4 rover1)
	(calibration-target camera4 objective4)
	(supports camera4 colour)
	(supports camera4 high-res)
	(on-board camera5 rover5)
	(calibration-target camera5 objective4)
	(supports camera5 high-res)
	(on-board camera6 rover6)
	(calibration-target camera6 objective5)
	(supports camera6 colour)
	(supports camera6 high-res)
	(supports camera6 low-res)
	(visible-from objective0 waypoint0)
	(visible-from objective0 waypoint1)
	(visible-from objective0 waypoint2)
	(visible-from objective0 waypoint3)
	(visible-from objective0 waypoint4)
	(visible-from objective0 waypoint5)
	(visible-from objective0 waypoint6)
	(visible-from objective0 waypoint7)
	(visible-from objective0 waypoint8)
	(visible-from objective0 waypoint9)
	(visible-from objective0 waypoint10)
	(visible-from objective0 waypoint11)
	(visible-from objective0 waypoint12)
	(visible-from objective0 waypoint13)
	(visible-from objective0 waypoint14)
	(visible-from objective0 waypoint15)
	(visible-from objective0 waypoint16)
	(visible-from objective1 waypoint0)
	(visible-from objective1 waypoint1)
	(visible-from objective1 waypoint2)
	(visible-from objective1 waypoint3)
	(visible-from objective2 waypoint0)
	(visible-from objective2 waypoint1)
	(visible-from objective2 waypoint2)
	(visible-from objective2 waypoint3)
	(visible-from objective2 waypoint4)
	(visible-from objective2 waypoint5)
	(visible-from objective2 waypoint6)
	(visible-from objective2 waypoint7)
	(visible-from objective2 waypoint8)
	(visible-from objective2 waypoint9)
	(visible-from objective2 waypoint10)
	(visible-from objective2 waypoint11)
	(visible-from objective2 waypoint12)
	(visible-from objective2 waypoint13)
	(visible-from objective2 waypoint14)
	(visible-from objective2 waypoint15)
	(visible-from objective2 waypoint16)
	(visible-from objective2 waypoint17)
	(visible-from objective3 waypoint0)
	(visible-from objective3 waypoint1)
	(visible-from objective3 waypoint2)
	(visible-from objective3 waypoint3)
	(visible-from objective3 waypoint4)
	(visible-from objective3 waypoint5)
	(visible-from objective3 waypoint6)
	(visible-from objective3 waypoint7)
	(visible-from objective3 waypoint8)
	(visible-from objective3 waypoint9)
	(visible-from objective3 waypoint10)
	(visible-from objective3 waypoint11)
	(visible-from objective3 waypoint12)
	(visible-from objective3 waypoint13)
	(visible-from objective3 waypoint14)
	(visible-from objective3 waypoint15)
	(visible-from objective3 waypoint16)
	(visible-from objective3 waypoint17)
	(visible-from objective3 waypoint18)
	(visible-from objective3 waypoint19)
	(visible-from objective4 waypoint0)
	(visible-from objective4 waypoint1)
	(visible-from objective4 waypoint2)
	(visible-from objective4 waypoint3)
	(visible-from objective4 waypoint4)
	(visible-from objective4 waypoint5)
	(visible-from objective4 waypoint6)
	(visible-from objective4 waypoint7)
	(visible-from objective4 waypoint8)
	(visible-from objective4 waypoint9)
	(visible-from objective4 waypoint10)
	(visible-from objective4 waypoint11)
	(visible-from objective4 waypoint12)
	(visible-from objective4 waypoint13)
	(visible-from objective4 waypoint14)
	(visible-from objective4 waypoint15)
	(visible-from objective4 waypoint16)
	(visible-from objective4 waypoint17)
	(visible-from objective4 waypoint18)
	(visible-from objective4 waypoint19)
	(visible-from objective4 waypoint20)
	(visible-from objective4 waypoint21)
	(visible-from objective4 waypoint22)
	(visible-from objective4 waypoint23)
	(visible-from objective5 waypoint0)
	(visible-from objective5 waypoint1)
	(visible-from objective5 waypoint2)
	(visible-from objective5 waypoint3)
	(visible-from objective5 waypoint4)
	(visible-from objective5 waypoint5)
	(visible-from objective5 waypoint6)
	(visible-from objective5 waypoint7)
	(visible-from objective5 waypoint8)
	(visible-from objective5 waypoint9)
	(visible-from objective5 waypoint10)
	(visible-from objective5 waypoint11)
	(visible-from objective5 waypoint12)
	(visible-from objective5 waypoint13)
	(visible-from objective5 waypoint14)
	(visible-from objective6 waypoint0)
	(visible-from objective6 waypoint1)
	(visible-from objective6 waypoint2)
	(visible-from objective6 waypoint3)
	(visible-from objective6 waypoint4)
	(visible-from objective6 waypoint5)
	(visible-from objective6 waypoint6)
	(visible-from objective6 waypoint7)
	(visible-from objective6 waypoint8)
	(visible-from objective6 waypoint9)
	(visible-from objective6 waypoint10)
	(visible-from objective7 waypoint0)
	(visible-from objective7 waypoint1)
	(visible-from objective7 waypoint2)
	(visible-from objective7 waypoint3)
	(visible-from objective7 waypoint4)
	(visible-from objective7 waypoint5)
	(visible-from objective7 waypoint6)
	(visible-from objective7 waypoint7)
	(visible-from objective7 waypoint8)
	(visible-from objective7 waypoint9)
	(visible-from objective7 waypoint10)
	(visible-from objective7 waypoint11)
	(visible-from objective7 waypoint12)
	(visible-from objective7 waypoint13)
	(visible-from objective7 waypoint14)
	(visible-from objective7 waypoint15)
	(visible-from objective7 waypoint16)
	(visible-from objective7 waypoint17)
	(visible-from objective7 waypoint18)
	(visible-from objective7 waypoint19)
	(visible-from objective7 waypoint20)
)

(:goal (and
(communicated-soil-data waypoint8)
(communicated-soil-data waypoint23)
(communicated-soil-data waypoint7)
(communicated-soil-data waypoint11)
(communicated-soil-data waypoint13)
(communicated-soil-data waypoint20)
(communicated-rock-data waypoint7)
(communicated-rock-data waypoint14)
(communicated-rock-data waypoint22)
(communicated-rock-data waypoint16)
(communicated-rock-data waypoint12)
(communicated-rock-data waypoint10)
(communicated-rock-data waypoint9)
(communicated-rock-data waypoint21)
(communicated-rock-data waypoint18)
(communicated-image-data objective2 high-res)
(communicated-image-data objective0 high-res)
(communicated-image-data objective3 colour)
(communicated-image-data objective7 colour)
(communicated-image-data objective5 high-res)
	)
)

(:metric minimize (recharges))
)
