(define (problem roverprob1234) (:domain rover)
(:objects
	general - lander
	colour high-res low-res - mode
	rover0 - rover
	rover0store - store
	waypoint0 waypoint1 waypoint2 waypoint3 - waypoint
	camera0 - camera
	objective0 objective1 - objective
	)
(:init
	(visible waypoint1 waypoint0)
	(visible waypoint0 waypoint1)
	(visible waypoint2 waypoint0)
	(visible waypoint0 waypoint2)
	(visible waypoint2 waypoint1)
	(visible waypoint1 waypoint2)
	(visible waypoint3 waypoint0)
	(visible waypoint0 waypoint3)
	(visible waypoint3 waypoint1)
	(visible waypoint1 waypoint3)
	(visible waypoint3 waypoint2)
	(visible waypoint2 waypoint3)
	(= (recharges) 0)
	(at-soil-sample waypoint0)
	(in-sun waypoint0)
	(at-rock-sample waypoint1)
	(at-soil-sample waypoint2)
	(at-rock-sample waypoint2)
	(at-soil-sample waypoint3)
	(at-rock-sample waypoint3)
	(at-lander general waypoint0)
	(channel-free general)
	(= (energy rover0) 50)
	(in rover0 waypoint3)
	(available rover0)
	(store-of rover0store rover0)
	(empty rover0store)
	(equipped-for-soil-analysis rover0)
	(equipped-for-rock-analysis rover0)
	(equipped-for-imaging rover0)
	(can-traverse rover0 waypoint3 waypoint0)
	(can-traverse rover0 waypoint0 waypoint3)
	(can-traverse rover0 waypoint3 waypoint1)
	(can-traverse rover0 waypoint1 waypoint3)
	(can-traverse rover0 waypoint1 waypoint2)
	(can-traverse rover0 waypoint2 waypoint1)
	(on-board camera0 rover0)
	(calibration-target camera0 objective1)
	(supports camera0 colour)
	(supports camera0 high-res)
	(visible-from objective0 waypoint0)
	(visible-from objective0 waypoint1)
	(visible-from objective0 waypoint2)
	(visible-from objective0 waypoint3)
	(visible-from objective1 waypoint0)
	(visible-from objective1 waypoint1)
	(visible-from objective1 waypoint2)
	(visible-from objective1 waypoint3)
)

(:goal (and
(communicated-soil-data waypoint2)
(communicated-rock-data waypoint3)
(communicated-image-data objective1 high-res)
	)
)

(:metric minimize (recharges))
)
