(define (problem roverprob2312) (:domain rover)
(:objects
	general - lander
	colour high-res low-res - mode
	rover0 rover1 - rover
	rover0store rover1store - store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 - waypoint
	camera0 camera1 camera2 - camera
	objective0 objective1 - objective
	)
(:init
	(visible waypoint0 waypoint3)
	(visible waypoint3 waypoint0)
	(visible waypoint1 waypoint0)
	(visible waypoint0 waypoint1)
	(visible waypoint1 waypoint4)
	(visible waypoint4 waypoint1)
	(visible waypoint2 waypoint0)
	(visible waypoint0 waypoint2)
	(visible waypoint2 waypoint3)
	(visible waypoint3 waypoint2)
	(visible waypoint3 waypoint1)
	(visible waypoint1 waypoint3)
	(visible waypoint3 waypoint5)
	(visible waypoint5 waypoint3)
	(visible waypoint4 waypoint3)
	(visible waypoint3 waypoint4)
	(visible waypoint5 waypoint0)
	(visible waypoint0 waypoint5)
	(visible waypoint5 waypoint2)
	(visible waypoint2 waypoint5)
	(visible waypoint5 waypoint4)
	(visible waypoint4 waypoint5)
	(= (recharges) 0)
	(at-rock-sample waypoint0)
	(at-soil-sample waypoint1)
	(at-soil-sample waypoint2)
	(at-rock-sample waypoint2)
	(at-soil-sample waypoint3)
	(at-rock-sample waypoint3)
	(at-soil-sample waypoint4)
	(in-sun waypoint4)
	(at-soil-sample waypoint5)
	(at-rock-sample waypoint5)
	(at-lander general waypoint3)
	(channel-free general)
	(= (energy rover0) 50)
	(in rover0 waypoint1)
	(available rover0)
	(store-of rover0store rover0)
	(empty rover0store)
	(equipped-for-rock-analysis rover0)
	(equipped-for-imaging rover0)
	(can-traverse rover0 waypoint1 waypoint0)
	(can-traverse rover0 waypoint0 waypoint1)
	(can-traverse rover0 waypoint1 waypoint4)
	(can-traverse rover0 waypoint4 waypoint1)
	(can-traverse rover0 waypoint0 waypoint2)
	(can-traverse rover0 waypoint2 waypoint0)
	(can-traverse rover0 waypoint0 waypoint3)
	(can-traverse rover0 waypoint3 waypoint0)
	(can-traverse rover0 waypoint0 waypoint5)
	(can-traverse rover0 waypoint5 waypoint0)
	(= (energy rover1) 50)
	(in rover1 waypoint4)
	(available rover1)
	(store-of rover1store rover1)
	(empty rover1store)
	(equipped-for-soil-analysis rover1)
	(equipped-for-imaging rover1)
	(can-traverse rover1 waypoint4 waypoint1)
	(can-traverse rover1 waypoint1 waypoint4)
	(can-traverse rover1 waypoint4 waypoint3)
	(can-traverse rover1 waypoint3 waypoint4)
	(can-traverse rover1 waypoint4 waypoint5)
	(can-traverse rover1 waypoint5 waypoint4)
	(can-traverse rover1 waypoint1 waypoint0)
	(can-traverse rover1 waypoint0 waypoint1)
	(can-traverse rover1 waypoint5 waypoint2)
	(can-traverse rover1 waypoint2 waypoint5)
	(on-board camera0 rover0)
	(calibration-target camera0 objective0)
	(supports camera0 colour)
	(supports camera0 low-res)
	(on-board camera1 rover0)
	(calibration-target camera1 objective1)
	(supports camera1 colour)
	(supports camera1 low-res)
	(on-board camera2 rover1)
	(calibration-target camera2 objective0)
	(supports camera2 colour)
	(supports camera2 high-res)
	(visible-from objective0 waypoint0)
	(visible-from objective0 waypoint1)
	(visible-from objective0 waypoint2)
	(visible-from objective0 waypoint3)
	(visible-from objective0 waypoint4)
	(visible-from objective0 waypoint5)
	(visible-from objective1 waypoint0)
	(visible-from objective1 waypoint1)
)

(:goal (and
(communicated-soil-data waypoint5)
(communicated-soil-data waypoint1)
(communicated-soil-data waypoint4)
(communicated-soil-data waypoint2)
(communicated-rock-data waypoint0)
(communicated-rock-data waypoint2)
(communicated-rock-data waypoint3)
(communicated-image-data objective0 colour)
(communicated-image-data objective1 low-res)
(communicated-image-data objective0 low-res)
	)
)

(:metric minimize (recharges))
)
